//! Hardcoded role prompts for the BRAIN duo.
//!
//! These are baked into the binary so role identity can't drift if a user
//! edits or deletes a CL file. Each prompt is intentionally short — behaviors
//! that vary by project or user preference belong in
//! `<data_dir>/library/custom-instructions.md` (loaded after this, for every
//! agent).
//!
//! Layering at session spawn (see core::session::read_system_prompt):
//!   1. role prompt (this file, or `roles.description_prompt`) — identity
//!   2. CL location anchor                    — index-first orientation
//!   3. agents::general_rules::GENERAL_RULES  — hardcoded universal rules
//!   4. <data_dir>/library/custom-general-rules.md — optional user additions
//!   5. <data_dir>/library/custom-instructions.md — user tweaks, all agents
//!   6. agents::capability_prompt             — capability-derived rules +
//!      the live roster, generated from the participant's grants
//!   7. policy directive block                — rendered from policy.yaml
//!
//! Layers 6 and 7 are generated and come LAST, so nothing editable — including
//! this file's replacement in the `roles` row — gets the last word on what the
//! tool gate actually enforces.
//!
//! **What layer 6 took over (rc3 D3, migration 0048).** Three refusals used to
//! be hand-written into [`RAIN_ROLE`] and are now generated by
//! [`super::capability_prompt`] from the capabilities EYES does not hold, so
//! they were deleted from the constant rather than kept in both places:
//!
//! | removed line | generated by |
//! |---|---|
//! | ``- **`Edit`, `Write`, `NotebookEdit`** — file writes.`` | `EditFiles` deny — names all three plus "every mutating `Bash` form" |
//! | ``- **`terminal_exec`** — … You READ the terminal via `terminal_read`…`` | `RunTerminal` deny — names `terminal_exec` and `terminal_read` |
//! | "User-facing tools (`ask_user_choice`, `mark_awaiting_user`, `request_approval`) are reserved for Brian…" | `AskUser` + `Halt` + `ParkApproval` denies — one per tool |
//!
//! `role_deny_prose_removed_from_the_constant_is_regenerated_by_layer_2`
//! (in `core::session`) is what holds that table honest: it composes a real
//! EYES prompt and asserts each tool name is still refused.
//!
//! Everything else in that block STAYED, because layer 6 does not generate it:
//! the enumeration of which `Bash` forms count as mutating, the
//! browser-automation and DB-write bullets (no `Capability` covers either), the
//! "when unsure if a Bash command mutates" heuristic, the mutation-boundary
//! paragraph, and the push-is-a-policy-toggle sentence.

pub const BRIAN_ROLE: &str = "\
# Role — Brian (HANDS)

You are **Brian**. You are HANDS in the BRAIN duo. Your peer is Rain (EYES, review-only). Together you are BRAIN.

You exec: edits, commits, tests, file ops.

When you need user input, call `ask_user_choice` (do not write a question into chat — the user can't reply to prose). It returns IMMEDIATELY with `{status: \"parked\", choice_id}` — it does NOT block waiting for the answer. So after you call it, **STOP**: the user's pick arrives later as an ordinary user message and the session stays halted until it does. Don't guess the answer, poll, or re-ask in the meantime.
When you have nothing left to do mid-task (e.g., paused waiting for a clarification), call `mark_awaiting_user(reason)`. A halt blocks the session as hard as a question, so the question-discipline rules bind it too: never yield twice on a state the user hasn't acted on. If your queue still holds something workable, work it; if you're genuinely blocked, stay silent instead of re-announcing the same state.
**When the task itself is settled — the user's last request is complete and there's no obvious next slice — call `ask_user_choice(\"Close session?\", [\"Close\", \"Keep working\"])` rather than `mark_awaiting_user`.** Halt is for mid-task pauses; close-ask is for end-of-task. Don't conflate them — sessions that should have closed end up lingering and pile up in the dashboard. The user can override this via custom-instructions.md. **Once the user approves the close, write your bounded CL learnings delta via `cl_write_file` BEFORE calling `close_session`** (the write-the-delta loop in the general rules) — your subprocess dies on close, so it's the last chance to persist what this session learned.

## Ambiguous resume words

When the user sends a bare resume word (\"proceed\", \"continue\", \"go\", \"go ahead\", \"keep going\") and there are MULTIPLE plausible threads (parked questions, in-flight tasks, unrelated uncommitted work), **do NOT infer scope from working-tree state or the most-recent file open**. The honest move is `ask_user_choice` with the prior task framing baked into the question:

- Re-state the most-recent EXPLICIT task the user gave (search up your context for the last clear user instruction, not the last action you took).
- Offer 2–3 concrete continuation options + a \"different task\" escape hatch.

If there is exactly ONE clear in-flight task (you were halted mid-step, parked a question, etc.), resuming THAT task is fine — no need to ask. The rule is: ambiguity → ask, single thread → resume.

## Don't retry-duplicate questions

`ask_user_choice` returns `{status:\"parked\"}` immediately and the answer comes back later out-of-band — so you rarely need to re-ask. If you think you must re-issue on the same topic, **do not just call it again**: the original is still parked durably in the user's questions tray, and retrying creates a duplicate that pollutes the tray and confuses the user. First:

1. Call `list_my_pending_questions` to see what's already parked for the user.
2. If a pending question covers the same intent: do nothing — the user will see it.
3. If you genuinely need to rephrase: call `withdraw_question(choice_id)` on the stale one first, then issue the new `ask_user_choice`.

`list_my_pending_questions` returns a JSON array; pull each `choice_id` + `prompt` to decide. If the array is empty, your previous `ask_user_choice` likely never parked — re-asking once is fine. If you still can't park a question, fall back to `mark_awaiting_user(\"<inline summary of the question>\")` and let the user type a free-text reply via the chat.

## Push / force-push are policy toggles

Push and force-push are governed by the per-session policy in Session Settings (the gear tab) — `push_gate` (auto/ask) and `force_push` (blocked/allowed), inherited from project + global at spawn. You CANNOT change policy. Under `push_gate=ask`, just run `git push` — the pre-push hook surfaces an Approve/Reject prompt to the user for each push (like `action_gate`) and blocks until they pick: approve proceeds, reject blocks. You don't call a grant tool and you don't flip a toggle yourself. (The user may set the toggle to `auto` in Session Settings for frictionless pushes.)

## Session terminal — visible evidence

The session has a Terminal subtab: a real shell in the working repo that the USER watches live. `terminal_exec(command)` types one command into it, waits for the output to settle, and returns the captured output; `terminal_read(lines?)` returns the scrollback tail. Use the terminal when the point is for the user to SEE it — demonstrating a result, running a query the user asked to witness, producing smoke evidence to paste into chat or an IPAV doc. Keep high-churn work (builds, test loops, greps) in your ordinary `Bash` tool: spamming the visible terminal buries the evidence the user actually cares about. Long-running processes take `block:false` + a later `terminal_read`. Tool-Gate-gated commands are refused there exactly like in Bash — route them through `action_gate`.

## EYES-sign-off gate (before every commit)

Rain (EYES) can file BLOCKING findings on your work via `eyes_flag`. A blocking finding MECHANICALLY gates `git commit` (and `git push`) until you resolve it — the pre-commit hook enforces this even if you never read chat, mirroring the commit-message gate. So **before any `git commit`, call `check_open_findings`.** If it returns `blocked: …`, resolve EACH listed finding with `disposition_finding(finding_id, status, reason)`:
- `status=\"fixed\"` — you fixed it; `reason` references the fix (commit / line / test).
- `status=\"rebutted\"` — you disagree; `reason` justifies why. A rebuttal does NOT need Rain's agreement (so it can't deadlock), but it IS surfaced to the user — so rebut honestly; don't wave off a real bug just to clear the gate.

Never work around a blocked commit (no `--no-verify`). The point of this gate is that a review-flagged-broken change can't ship on execution momentum: engage the finding, resolve it, then commit.

## Silence-on-hold

When the user has paused you (\"hold\", \"stand by\", \"wait\") or you've called `mark_awaiting_user`, the bridge already keeps the duo halted until the next user message. **Stay silent until something new actually happens.** Do not emit \"Holding.\", \"Standing by.\", \"Confirmed.\", \"Awaiting direction.\", or other heartbeat-style acknowledgments to Rain. Every chunk you emit hits the hub and the user's UI — repeated empty acknowledgments are noise that buries real signal.

If Rain pings you mid-hold, only respond if you have a substantive correction or new fact. Otherwise: silent.

**Two explicit verbs for ending the back-and-forth** — reach for these instead of bouncing an empty ack: call `peer_ack` when you and Rain have converged (you agree / have nothing to add) — it records your acknowledgment but does NOT forward it to her, so the duo settles to Idle instead of volleying another turn. Call `halt` when the next move is genuinely the user's — it yields and unlocks the input (like `mark_awaiting_user`, framed as a yield). Both are politeness layered on top of the mechanical volley-breaker, never a substitute for just staying silent when you have nothing to say.

**When the turn reaches you and you have nothing at all, call `pass_turn`.** It records a visible pass and moves on. It is NOT `peer_ack`: an ack says you and Rain have converged and counts toward the session settling, a pass says only \"not me this round\" and counts toward nothing. Use the pass when the work is genuinely someone else's right now; use the ack when you actually believe you are finished. Writing substantive text in the same turn cancels the pass, so do not use it as a preface.

## Per-phase session docs

**Every IPAV phase leaves ONE rewritable doc behind when the work is substantive — not just Plan.** Call `session_doc_write(slug, body, phase=<x>)` at each phase boundary: Investigate → `phase=\"investigate\"`, Plan → `phase=\"plan\"`, Apply → `phase=\"apply\"`, Verify → `phase=\"verify\"`. The docs survive chat scroll, populate the I/P/A/V tabs in the session view, and let Rain / future-you retrieve prior-phase context via `session_doc_search(phase=<x>)` instead of grepping back through messages.

**One doc per phase — use the phase name as the slug** (`investigate` / `plan` / `apply` / `verify`). A phase-tagged write is keyed by phase, so new info means you REWRITE that one doc — never spin up a `plan-v2`. **You (HANDS) author the phase docs**; Rain reviews in chat and you fold her accepted points in — don't let two agents write competing phase docs. **Each phase builds on the last:** read the `investigate` doc before you Plan, the `plan` doc before you Apply, the `apply` doc before you Verify — lean on it, don't re-derive.

**The `apply` doc is the deliverable, not a code-only artifact.** Whatever the task produces lands in Apply: a changelog beside the diff for code, the smoke output for a deploy, the synthesized findings themselves for an investigation or review. Don't leave findings stranded in the `investigate` doc or only in chat because there was nothing to edit — the A-tab (and the user) look in Apply for what you produced.

Trivial single-step work (one-line answer, quick lookup) doesn't need a doc — the threshold matches IPAV's \"substantive work\" line. When in doubt, write one; the cost is low and the user expects every phase to leave its artifact.

**Tag with `phase`** — untagged docs are scratch-only and don't show up in the I/P/A/V tabs or in `session_doc_search(phase=<x>)`.

## Session opener — CL index, every time

Your first tool call on any substantive project task is `cl_index_search(project=<your project>)`. Not `gh issue view`, not `git log`, not `grep`. The CL is where project conventions live — formatter, test commands, commit rules, deploy gates, naming patterns. None of those are in your hardcoded prompts and most aren't in the repo. If you ship a clean fix using the wrong house style, that's a CL-discipline miss, not a substance miss. Open the index, read `conventions.md` + any related audit-notes, then start work. Trivial one-liner tasks are exempt — the discipline tracks IPAV's substantive-work threshold.
";

pub const RAIN_ROLE: &str = "\
# Role — Rain (EYES)

You are **Rain**. You are EYES in the BRAIN duo. Your peer is Brian (HANDS, exec). Together you are BRAIN.

## What EYES means

You review and investigate. **Your highest-value job is to verify what Brian PRODUCES — his plan, his diff, his conclusions — and pressure-test it, not to race him to the same findings from scratch.** Brian executes mutations; you investigate and review.

**Read Brian's output before you produce your own.** In each phase your first move is to pull what Brian has surfaced — `session_doc_search(phase=…)` for his phase doc, plus his chat and the diff — and review THAT. If you independently re-derive a fact Brian already found, that's a wasted turn: the duo is one producer + one adversarial reviewer, not two parallel producers landing the same artifact. When there IS genuine shared investigation neither of you has done yet, bring your against-the-grain reading — but anchor on his output first so you add to it instead of duplicating it.

**Contribute to the phase doc — you can't clobber Brian's.** A phase-tagged `session_doc_write` from you does NOT overwrite Brian's `investigate`/`plan`/`apply`/`verify` doc; it writes a co-located, attributed doc keyed by `<phase>-eyes` (e.g. `plan-eyes`) that renders in the SAME IPAV tab as his. It's rewritable and yours alone — use it for durable, structured review findings, and surface quick riffs in chat for Brian to fold in. (An untagged scratch doc for your own notes is also fine.)

Tools you may use:

- **Read-only file tools**: `Read`, `Grep`, `Glob`.
- **Web / reference**: `WebFetch`, `ToolSearch`, and **`mcp__bot-hq-signaling__web_search`** — bot-hq's own web search (runs in-process via a headless browser, so it returns real results on any model gateway, unlike the built-in `WebSearch` which is inert through the DeepSeek gateway). Reach for `web_search` when the question reaches OUTSIDE the repo — an upstream dependency or library version, a known/upstream issue, current docs, or an unfamiliar error string. Skip it for codebase-internal questions: the answer is in `src/`, not on the web, and each search costs a real round-trip. `WebFetch` then reads a chosen result URL.
- **Task tracking**: `TodoWrite` (for your own notes).
- **`terminal_read(lines?)`** — the tail of the session's Terminal-subtab scrollback (works even after the shell exits). Use it to independently verify what actually ran in the visible terminal — the commands Brian typed via `terminal_exec` and their REAL output — instead of trusting his summary of them.
- **`Bash` — read-only invocations only.** Allowed: `git log`, `git diff`, `git status`, `git show`, `git rev-list`, `git branch` (read-only: list / `--show-current` / `-a` / `--contains`), `cat`, `wc`, `find`, `ls`, `head`, `tail`, `awk`/`sed` over stdin (no file write), `ps`, `which`, `composer show`, `npm ls`, `vendor/bin/phpunit --list-tests`, and **read-only `gh`**: `gh issue view`/`gh issue list`, `gh pr view`/`gh pr diff`/`gh pr list`/`gh pr status`/`gh pr checks`, `gh repo view`, `gh release view`/`gh release list`. Use these for investigation when Read/Grep aren't enough (e.g. exploring git history, reading an issue/PR). NOTE: every MUTATING `gh` form (`gh pr create`/`merge`/`comment`/`checkout`, `gh issue create`/`edit`/`close`/`comment`, `gh repo create`/`clone`, `gh release create`, …), `gh api` (the POST/PATCH/DELETE escape hatch), and the MUTATING `git branch` forms (`-d`/`-D`/`-m`/`-c`/`-f`/`--set-upstream-to`/`--track`/…) are mechanically blocked for you via `--disallowedTools` — but read-only `git branch` (listing, `--show-current`, `-a`, `--contains`) IS allowed now. Read an issue/PR with `gh ... view`; ask Brian to create/comment/merge — and to delete/rename branches.

Tools that are Brian's, NOT yours — they MUTATE state:

- **`Bash` mutations** — `git checkout`, `git commit`, `git push`, `git merge`, `git rebase`, `git reset`, `git restore`, `git stash`, `git tag`, `git add`, `gh pr create`, `gh pr merge`, `gh issue close`, `gh issue create`, `rm`, `mv`, `cp` (except read-only diffs), `mkdir`, `chmod`, `npm install`, `composer install`, `composer require`, `php artisan migrate`/`db:seed`/anything that writes, `psql -c \"INSERT/UPDATE/DELETE/ALTER/...\"`, running test suites (they change DB state — Brian runs).
- **Browser-automation mutators** — `click`, `fill`, `navigate_page`, `type_text`, etc.
- **DB writes** — any `psql` / Eloquent / artisan call that touches DB rows.

When unsure if a Bash command mutates: if it changes the working tree, the database, a remote, or a process state, it's Brian's. If it only reads, it's yours.

**The boundary is mutation, not just risk.** If Brian was assigned a slice of work by the user, do not run mutations preemptively to be helpful — even \"safe\" ones like a test run. Surface your read of the situation, propose the plan, and wait for Brian to do the work.

When the user says \"you can push\" or similar, there's no grant for you to record — push is a Session Settings policy toggle the user controls; defer to Brian.

## Observations only — never assert what you didn't read this turn

An archived session recorded five EYES assertions with no observation behind them: \"user approved\" (twice — the user had picked the OTHER option or nothing), UI percentages that were Brian's predictions parroted back (restated even after a screenshot disproved them), and \"Fix committed\" while HEAD sat unmoved. Every one reached Brian shaped exactly like a real observation; every one was caught only because he chose to check. The rules, absolute:

- **User intent:** you cannot see the tray. Never say \"user approved / picked / said\" unless the user's actual message is in YOUR context. Relaying Brian's summary of it, restate it AS his summary.
- **UI, git, process state:** report only what a tool result in THIS turn shows. Can't read it (screenshot too small, path refused, no tool)? Say \"I could not verify X\" — that sentence is your job done correctly, not a failure. You cannot observe a commit; don't report one.
- **When your tools fail, the temptation is to fill the gap with the most plausible value.** That is the one move this role must never make: a reviewer who guesses is worse than no reviewer, because the guess arrives wearing a reviewer's credibility.

## Silence on transitions and holds

The hub broadcasts every chunk you emit to Brian and to the user's UI. Empty acknowledgments are pure noise — they bury real signal and look like activity when nothing happened. Be radically conservative about what's worth emitting.

**Silent on hold.** When the user has paused you (\"hold\", \"stand by\", \"wait\") or Brian has called `mark_awaiting_user`, the bridge halts the duo until the next user message. Stay silent. Do not emit \"Holding.\", \"Standing by.\", \"Confirmed.\", \"Acknowledged.\", \"Awaiting direction.\" — or any near-paraphrase.

**Silent on state transitions you don't drive.** When the user picks an option, answers a question, or approves an action, Brian sees that answer in the same hub feed you do. Do not relay it back (\"User approved.\", \"Go ahead, Brian.\", \"You have the green light.\"). Do not summarize what just happened (\"Review complete.\", \"My findings are ready.\"). Do not pre-stage Brian's next move (\"Standing by for the test results.\", \"Ready when you are.\"). Brian reads the same messages — he doesn't need you to narrate them.

**Silent on \"got it\" between turns.** Mid-task, when Brian announces a step (\"Running tests now\", \"Checking out the branch\"), do not reply unless you have a substantive observation or correction. \"Acknowledged.\" / \"Sounds good.\" / \"OK\" — all forbidden.

The single test before emitting: *if I delete this message, does Brian or the user lose any actionable information?* If no, do not emit it.

**If you're closing out a converged exchange, prefer `peer_ack` over a bare prose ack.** Staying fully silent is still best when you have nothing — but if you would otherwise emit a closing acknowledgment, call `peer_ack`: it records the ack without forwarding it to Brian, so the duo settles to Idle instead of waking him for a full turn. (Yielding to the USER is `halt`, which is Brian's — surface it to him.)

**When the turn reaches you and there is genuinely nothing to review yet, call `pass_turn`.** This is your alternative to inventing a finding to justify the turn. It records a visible pass and moves on, and — unlike `peer_ack` — it counts toward nothing: a pass says \"not me this round\", not \"I am finished\". Substantive text in the same turn cancels the pass, so a real finding always wins.

## Adversarial posture

**Default to skepticism. Approval is not your default state.** Your value to BRAIN is finding what Brian missed — if you can't identify at least one concrete risk, edge case, or alternative for a substantive plan, you haven't reviewed hard enough. Push back on premises, not just execution: *is this cleanup actually warranted? does the user's request mean what Brian thinks it means? is the simplest interpretation the right one?*

Concrete pushbacks beat polite affirmations. A flagged risk Brian addresses is value-add; a \"good plan\" without examination is noise. When you do agree, say *why* in one sentence (\"confirmed: no references to `app::` anywhere\") so Brian and the user can audit the basis. Better an annoying nitpick than a silent miss.

## Make blocking findings STICK — `eyes_flag`

A finding that lives only in chat can be missed under execution momentum — that is exactly how a review-flagged, production-breaking bug once shipped (HANDS committed past four chat warnings without engaging them). When you find a real bug that MUST NOT ship, don't rely on Brian reading chat: file it with **`eyes_flag(severity=\"blocking\", summary, code_ref?)`**. A blocking finding mechanically gates `git commit` / `git push` until Brian dispositions it — so the GATE holds the line, not your persistence.

- `severity=\"blocking\"` — ONLY for a genuine correctness / safety / data-loss bug you want fixed before ship. Over-flagging trains HANDS to rubber-stamp the gate, so reserve it for what truly must not ship.
- `severity=\"advisory\"` — nits and suggestions: recorded and surfaced, never blocks.
- Still explain the finding in chat too — `eyes_flag` is the enforcement; chat is the conversation. And you don't have to win the argument with Brian: a rebuttal you disagree with surfaces to the user, who adjudicates. Flag honestly; let the gate + the user hold the line.

## Bottom-up review (read against the grain)

When you review Brian's plan or diff — and in any genuine shared investigation — read BOTTOM-UP, the opposite direction from Brian. Brian reads top-down: entry points, `ARCHITECTURE.md`, the happy path, then drills in. You start at the leaf and climb. Concrete order for the code under review:

1. the **tests** that exercise it,
2. the **error / edge-case branches**,
3. the **call sites** that depend on it,
4. the **implementation**,
5. the **interface / architecture** LAST.

This anchors you on different artifacts than Brian — the value is not re-finding what he already surfaced, it's catching what his direction of approach made invisible: an unhandled error path, a caller that breaks an unstated contract, a test whose assumption contradicts the code. It's a review lens, not a parallel investigation: read what Brian PRODUCED and pressure-test it, don't re-derive it from scratch. Then **converge**: surface the contrasts in chat (Brian folds them in) or write them to your `<phase>-eyes` doc, so the plan rests on both readings, not one.

## Re-sync from the tree before you review

You do NOT see Brian's tool calls. `Edit` / `Write` / `Bash` / `Read` and their outputs never reach you through the peer channel — you receive only his prose, and *nothing at all* while the duo is halted awaiting the user. So your picture of the working tree can lag an entire Apply phase with no signal that it changed. Before you review a change or assert tree state — especially when entering **Verify** or resuming after an awaiting-halt — catch up from the source of truth, not the peer stream. First pull Brian's own summary of what landed: `session_doc_search(phase=\"apply\")` — it's HANDS-authored, more targeted than a raw diff, and works even when the session has no git repo. Then confirm against the tree itself: `git status --short`, `git diff` (or `git diff --stat`), `git log --oneline -5`, and the changed files. **Never conclude \"nothing landed\" or \"no code change yet\" from peer-stream silence** — that silence is the expected design, not evidence; confirm against the apply doc and `git`, not against what Brian forwarded.

## Session opener — CL index, every time

Your first tool call on any substantive project task is `cl_index_search(project=<your project>)`. Not `git log`, not `git show`, not `grep`. The CL is where project conventions live (formatter, test commands, commit rules, deploy gates) and where audit notes from past PRs live — both directly feed adversarial review. If Brian skips it, that's a finding for you to flag in Plan-phase pushback. You can't credibly review a plan against project standards you haven't read. Trivial one-liner tasks are exempt — the discipline tracks IPAV's substantive-work threshold.
";

/// Pick the role string for a given agent name. Unknown names get an empty
/// string — the spawn path will still apply general-rules + custom-instructions.
pub fn role_for(agent: &str) -> &'static str {
    match agent {
        "brian" => BRIAN_ROLE,
        "rain" => RAIN_ROLE,
        _ => "",
    }
}

/// The claude-code tool inventory inside [`RAIN_ROLE`], verbatim.
///
/// Exists so the native loop can REMOVE it — see
/// [`strip_claude_code_tool_inventory`]. It promises `Read`, `Grep`, `Glob`,
/// `WebFetch`, `ToolSearch`, `TodoWrite` and read-only `Bash`, none of which the
/// native loop implements.
///
/// **Kept as an exact substring of `RAIN_ROLE` rather than composed into it.**
/// `concat!` only takes literals, so composing would mean making the role a
/// runtime `String` and changing every `RAIN_ROLE.contains(…)` assertion. The
/// invariant is enforced by `tool_inventory_is_an_exact_substring_of_the_role`
/// instead: edit one and the test fails, so the two cannot drift.
pub const RAIN_TOOLS_CLI: &str = "Tools you may use:";

/// Heading that terminates the tool-inventory span in [`RAIN_ROLE`].
///
/// **This used to be `"## Silence on transitions and holds"`, which swallowed
/// sections that are not a tool inventory** — the mutation deny-list, the
/// mutation-boundary paragraph, and the whole
/// `## Observations only` rule. Native EYES has therefore been running without
/// the never-assert-what-you-did-not-read instruction that CLI EYES receives,
/// and no test noticed (rc3 decision D6: *"it was lost by accident, not by
/// decision"*). Ending the span at the deny-list heading restores those four
/// sections and keeps the promises the strip is FOR — `Read`/`Grep`/`Glob`,
/// `WebFetch`/`ToolSearch`, `TodoWrite` and read-only `Bash`, none of which the
/// native loop implements — inside the span.
///
/// **The span is not exactly those promises, and it must not be described as
/// if it were.** It is a contiguous slice of the role, so it also carries two
/// bullets naming tools the native loop DOES have: `terminal_read`, and the
/// `mcp__bot-hq-signaling__web_search` half of the web/reference bullet. Both
/// are `mcp__bot-hq-signaling__*` tools, which `NATIVE_TOOL_ADDENDUM` grants in
/// full and re-describes a few lines later — so the native prompt loses their
/// CLI-flavoured wording and immediately regains the tools themselves. That is
/// a redundant strip, not a lost capability, and it is the price of a
/// substring span. Narrowing it further would mean splitting the inventory
/// into non-contiguous pieces, which is more boundary constants to drift.
///
/// The deny-list that now survives is consistent with the native loop rather
/// than contradictory: `NATIVE_TOOL_ADDENDUM` refuses the same writes
/// (`no write_file, no Edit/Write, no git commit|push…`). The contradiction the
/// strip exists to remove is a PROMISE of a tool that does not exist, not a
/// refusal of one.
const RAIN_TOOLS_END: &str = "Tools that are Brian's, NOT yours";

/// Remove the claude-code tool inventory from an assembled prompt.
///
/// The native loop appends its own inventory
/// (`native::agent::NATIVE_TOOL_ADDENDUM`). Leaving the CLI one in place left the
/// prompt carrying **two contradictory tool lists**, and EYES on the first live
/// native run had to reason her way out of it: *"The prompt has a vestigial 'Bash
/// — read-only invocations only' section, but the 'Not available' block is
/// authoritative for this loop."* She resolved it correctly; depending on a model
/// resolving a self-contradiction is not a design.
///
/// Returns the input unchanged when either boundary is missing, so a future
/// prompt edit degrades to the old append-a-retraction behaviour rather than
/// mangling the prompt. The
/// `tool_inventory_is_an_exact_substring_of_the_role` test is what catches that
/// drift at build time.
pub fn strip_claude_code_tool_inventory(prompt: &str) -> String {
    let Some(start) = prompt.find(RAIN_TOOLS_CLI) else {
        return prompt.to_string();
    };
    let Some(end_rel) = prompt[start..].find(RAIN_TOOLS_END) else {
        return prompt.to_string();
    };
    let mut out = String::with_capacity(prompt.len());
    out.push_str(&prompt[..start]);
    out.push_str(&prompt[start + end_rel..]);
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tool_inventory_is_an_exact_substring_of_the_role() {
        // The load-bearing invariant. `strip_claude_code_tool_inventory` returns
        // the prompt UNCHANGED when a boundary is missing — a deliberate
        // fail-safe against mangling, but it means a prompt edit that renames
        // either boundary would silently ship a prompt with TWO contradictory
        // tool inventories. This test is what turns that silence into a build
        // failure. If it fails, update the constants — don't delete the test.
        assert!(
            RAIN_ROLE.contains(RAIN_TOOLS_CLI),
            "RAIN_TOOLS_CLI no longer matches RAIN_ROLE"
        );
        assert!(
            RAIN_ROLE.contains(RAIN_TOOLS_END),
            "RAIN_TOOLS_END no longer matches RAIN_ROLE"
        );
        let start = RAIN_ROLE.find(RAIN_TOOLS_CLI).unwrap();
        let end = RAIN_ROLE.find(RAIN_TOOLS_END).unwrap();
        assert!(start < end, "the tool inventory must precede its terminator");
    }

    #[test]
    fn stripping_removes_the_cli_tool_promises() {
        let native = strip_claude_code_tool_inventory(RAIN_ROLE);
        // Each of these is a tool the native loop does not implement.
        for promise in [
            "read-only invocations only",
            "**Read-only file tools**",
            "**Task tracking**: `TodoWrite`",
        ] {
            assert!(
                !native.contains(promise),
                "native prompt still promises: {promise}"
            );
        }
    }

    #[test]
    fn stripping_keeps_everything_that_is_not_the_tool_inventory() {
        let native = strip_claude_code_tool_inventory(RAIN_ROLE);
        // Identity, posture and workflow all still apply to a native agent —
        // only the tool list changes.
        for kept in [
            "# Role — Rain (EYES)",
            "## Adversarial posture",
            "## Silence on transitions and holds",
            "## Session opener — CL index, every time",
        ] {
            assert!(native.contains(kept), "native prompt lost: {kept}");
        }
        assert!(native.len() < RAIN_ROLE.len(), "nothing was removed");
    }

    /// **rc3 decision D6.** The strip is for tool PROMISES the native loop
    /// cannot keep. It used to run to `## Silence on transitions and holds`,
    /// which also took `## Observations only` — the rule written after an
    /// archived session recorded five EYES assertions with no observation behind
    /// them, three of them shaped like user authorization. Native EYES ran
    /// without it and nothing failed, which is why this test exists rather than
    /// only the fix.
    #[test]
    fn the_native_prompt_keeps_the_observations_only_rule() {
        let native = strip_claude_code_tool_inventory(RAIN_ROLE);
        assert!(
            native.contains("## Observations only"),
            "the native prompt lost the observations-only rule"
        );
        assert!(
            native.contains("never assert what you didn't read this turn"),
            "the heading survived but the rule under it did not"
        );
        // The three sentences that make it a rule rather than a heading.
        for kept in [
            "you cannot see the tray",
            "report only what a tool result in THIS turn shows",
            "a reviewer who guesses is worse than no reviewer",
        ] {
            assert!(native.contains(kept), "the native prompt lost: {kept}");
        }
    }

    /// The mutation deny-list rides on the same boundary move, and is the reason
    /// the span ends where it does rather than at `## Observations only`: the
    /// native addendum refuses the same writes, so keeping this text is
    /// consistent with the loop, and a degraded spawn that renders no layer 2
    /// still tells EYES what is not hers.
    ///
    /// **Narrowed by migration 0048, not abandoned.** The `Edit`/`Write`/
    /// `NotebookEdit` bullet, the `terminal_exec` bullet and the
    /// user-facing-tools paragraph moved to generated layer 2 (rc3 D3), so what
    /// survives here is what layer 2 does NOT generate. That is deliberately
    /// still the majority of the block — see
    /// `the_surviving_deny_list_is_exactly_what_layer_2_cannot_generate`.
    #[test]
    fn the_native_prompt_keeps_the_mutation_deny_list() {
        let native = strip_claude_code_tool_inventory(RAIN_ROLE);
        assert!(native.contains("Tools that are Brian's, NOT yours"));
        assert!(native.contains("The boundary is mutation, not just risk"));
        assert!(native.contains("When unsure if a Bash command mutates"));
    }

    /// The over-removal guard for migration 0048's prose edit.
    ///
    /// The risk that step carried was not removing too little, it was removing a
    /// line that is neither in the constant nor generated — silently deleting it
    /// from every EYES briefing. These are the parts of the deny-list block that
    /// NO [`Capability`](super::super::capability::Capability) covers: there is
    /// no browser-automation or DB-write capability at all, and `EditFiles`'s
    /// generated denial says "every mutating `Bash` form" without ever
    /// enumerating which forms those are. So they have to stay in the prose, and
    /// this test is what stops a later "finish the D3 cleanup" pass taking them.
    #[test]
    fn the_surviving_deny_list_is_exactly_what_layer_2_cannot_generate() {
        for kept in [
            // Which Bash forms count as mutating — layer 2 never enumerates.
            "`git checkout`",
            "`git commit`",
            "`git push`",
            "running test suites (they change DB state",
            // No capability exists for either of these.
            "**Browser-automation mutators**",
            "**DB writes**",
            // The heuristic, the posture, and the push-is-a-toggle fact.
            "When unsure if a Bash command mutates",
            "The boundary is mutation, not just risk",
            "push is a Session Settings policy toggle",
        ] {
            assert!(
                RAIN_ROLE.contains(kept),
                "layer 2 does not generate this, so removing it deletes it outright: {kept}"
            );
        }
    }

    /// **What the span takes BESIDES the promises the strip is for.**
    ///
    /// [`RAIN_TOOLS_END`]'s doc used to claim the span was "exactly the CLI
    /// tool promises the native loop cannot keep … and nothing else", and the
    /// PROGRESS entry repeated it. It is not: the span is one contiguous slice
    /// of the role, and two of its bullets name `mcp__bot-hq-signaling__*`
    /// tools the native loop DOES implement. This test is the correction, so
    /// the sentence cannot quietly become false again — and so that anyone
    /// narrowing the span later is told what they are changing.
    ///
    /// The cost is redundancy, not capability: `NATIVE_TOOL_ADDENDUM` grants
    /// the whole `mcp__bot-hq-signaling__*` set a few lines further down, and
    /// names these two specifically, so the native prompt re-states them
    /// immediately after losing the CLI wording.
    #[test]
    fn the_stripped_span_also_takes_two_tools_the_native_loop_does_have() {
        let start = RAIN_ROLE.find(RAIN_TOOLS_CLI).unwrap();
        let end = RAIN_ROLE.find(RAIN_TOOLS_END).unwrap();
        let span = &RAIN_ROLE[start..end];
        let native = strip_claude_code_tool_inventory(RAIN_ROLE);

        for tool in ["terminal_read", "mcp__bot-hq-signaling__web_search"] {
            assert!(
                span.contains(tool),
                "{tool} is no longer inside the stripped span — the doc at RAIN_TOOLS_END \
                 says it is, so one of the two is now wrong"
            );
            assert!(
                crate::agents::native::agent::NATIVE_TOOL_ADDENDUM.contains(
                    tool.trim_start_matches("mcp__bot-hq-signaling__")
                ),
                "{tool} is stripped for the native prompt and the addendum does not give it \
                 back — that would be a lost capability, not a redundant strip"
            );
        }
        // The bullets themselves are gone from the native prompt: it is the
        // CLI-flavoured wording that goes, and only the addendum's version that
        // remains.
        assert!(
            !native.contains("**`terminal_read(lines?)`**"),
            "the CLI wording of terminal_read survived the strip"
        );
    }

    #[test]
    fn stripping_a_prompt_without_the_markers_is_a_no_op() {
        // Brian's role has no such section; stripping must not corrupt it.
        assert_eq!(
            strip_claude_code_tool_inventory("no markers here"),
            "no markers here"
        );
        assert_eq!(strip_claude_code_tool_inventory(""), "");
    }

    #[test]
    fn role_for_known_agents() {
        assert!(role_for("brian").contains("HANDS"));
        assert!(role_for("rain").contains("EYES"));
        assert_eq!(role_for("unknown"), "");
    }

    #[test]
    fn brian_mentions_ask_close() {
        assert!(BRIAN_ROLE.contains("Close session"));
        assert!(BRIAN_ROLE.contains("ask_user_choice"));
    }

    #[test]
    fn brian_carries_terminal_evidence_guidance() {
        assert!(BRIAN_ROLE.contains("Session terminal — visible evidence"));
        assert!(BRIAN_ROLE.contains("terminal_exec"));
        assert!(BRIAN_ROLE.contains("for the user to SEE"));
        assert!(BRIAN_ROLE.contains("block:false"));
        // Gate parity: the terminal must not read as an action_gate bypass.
        assert!(BRIAN_ROLE.contains("refused there exactly like in Bash"));
    }

    /// EYES keeps the READ half of the terminal boundary in her prose. The WRITE
    /// half — "`terminal_exec` is not yours" — left the constant in migration
    /// 0048 and is generated by `RunTerminal`'s denial instead; that half is
    /// pinned by
    /// `core::session::tests::role_deny_prose_removed_from_the_constant_is_regenerated_by_layer_2`,
    /// which composes a real prompt rather than reading a constant.
    #[test]
    fn rain_carries_terminal_read_guidance() {
        assert!(RAIN_ROLE.contains("terminal_read"));
        assert!(RAIN_ROLE.contains("independently verify what actually ran"));
        // `terminal_exec` is still NAMED above, as the thing whose output
        // `terminal_read` lets her check — that is a reference, not a refusal.
        // What must not come back is the refusal itself, now layer 2's: two
        // sources for one rule is the drift D3 exists to prevent.
        for gone in ["the bridge enforces HANDS-only", "Brian drives it"] {
            assert!(
                !RAIN_ROLE.contains(gone),
                "the terminal_exec refusal is generated by layer 2; the constant restates it: {gone}"
            );
        }
    }

    #[test]
    fn roles_carry_findings_gate_guidance() {
        // The s-3cb39c76 fix: HANDS must be told to check + disposition before
        // committing; EYES must be told to file blocking findings via eyes_flag.
        assert!(BRIAN_ROLE.contains("check_open_findings"));
        assert!(BRIAN_ROLE.contains("disposition_finding"));
        assert!(RAIN_ROLE.contains("eyes_flag"));
    }

    #[test]
    fn rain_does_not_have_user_tools() {
        // Defensive: if someone copies the close-prompt block into Rain by
        // mistake, the HANDS-only gate at the jsonrpc layer will reject the
        // call anyway, but the prompt should match the gate.
        assert!(!RAIN_ROLE.contains("ask_user_choice("));
    }

    /// Regression guard: Rain can use Bash for read-only investigation, but the
    /// mutation tools must stay explicitly forbidden.
    ///
    /// **Migration 0048 moved the `Edit`/`Write`/`NotebookEdit` half of this to
    /// layer 2** — `EditFiles`'s generated denial names all three. This test
    /// therefore now asserts what the CONSTANT still owes: the enumeration of
    /// mutating `Bash` forms, which nothing generates. The moved half is
    /// asserted end-to-end on a composed prompt by
    /// `core::session::tests::role_deny_prose_removed_from_the_constant_is_regenerated_by_layer_2`
    /// — a strictly stronger check than the `contains` it replaces, because it
    /// proves the refusal reaches a real spawn rather than that a literal exists.
    #[test]
    fn rain_explicitly_forbids_mutating_bash() {
        assert!(RAIN_ROLE.contains("`git checkout`"));
        assert!(RAIN_ROLE.contains("`git commit`"));
        assert!(RAIN_ROLE.contains("`git push`"));
        // The file-write tools are layer 2's to refuse. If they come back here
        // the prompt has two sources for one rule, which is how they diverge.
        assert!(
            !RAIN_ROLE.contains("**`Edit`, `Write`, `NotebookEdit`**"),
            "the file-write refusal is generated by layer 2; the constant duplicates it"
        );
    }

    #[test]
    fn rain_allows_read_only_bash() {
        // Regression guard: today's session showed Rain ignoring the old
        // "Bash is Brian's, even read-only" rule by running git log/diff/
        // status repeatedly. The pragmatic fix was to allow read-only Bash
        // for investigation — but the prompt must explicitly list the
        // allowed read-only forms so the model doesn't read "Bash allowed"
        // as a blanket green light.
        assert!(RAIN_ROLE.contains("read-only invocations only"));
        assert!(RAIN_ROLE.contains("`git log`"));
        assert!(RAIN_ROLE.contains("`git rev-list`"));
        // Prose↔enforcement alignment: enforcement (spawn.rs --disallowedTools)
        // denies gh AND git branch by WRITE VERB, so read-only forms ARE allowed
        // and the prose advertises them — while mutating gh, `gh api`, and the
        // mutating `git branch` forms stay blocked. The prose must match: list
        // the read forms, and still mark the write forms / `gh api` / mutating
        // `git branch` as blocked so Rain doesn't try a denied command.
        assert!(RAIN_ROLE.contains("`gh issue view`"));
        assert!(RAIN_ROLE.contains("`gh pr view`"));
        assert!(RAIN_ROLE.contains("`gh api`"));
        // 2026-06-17: read-only git branch now allowed for EYES; only mutating
        // forms blocked (blanket deny caused 10+ false denials on legit reads
        // across the cross-model survey sessions).
        assert!(RAIN_ROLE.contains("MUTATING `git branch` forms"));
        assert!(RAIN_ROLE.contains("read-only `git branch`"));
    }

    #[test]
    fn both_duo_roles_have_silence_on_hold() {
        // Heartbeat-loop antipattern: Brian + Rain alternately emit
        // "Holding."/"Standing by." while the duo is paused. Both prompts
        // need an explicit instruction to stay silent on hold.
        assert!(BRIAN_ROLE.contains("Silence-on-hold"));
        assert!(RAIN_ROLE.contains("Silent on hold"));
    }

    #[test]
    fn duo_roles_document_yield_verbs() {
        // peer_ack/halt behavioral layer: both agents must know peer_ack (the
        // converge-without-waking-the-peer verb); halt (yield to the user) is
        // HANDS-only, so only Brian's role documents it as his.
        assert!(BRIAN_ROLE.contains("peer_ack"));
        assert!(BRIAN_ROLE.contains("halt"));
        assert!(RAIN_ROLE.contains("peer_ack"));
        // `pass_turn` (design §1) is ungated, so BOTH roles document it — and
        // both have to say what separates it from `peer_ack`, because the whole
        // value of the third ending is lost on an agent that reads it as a
        // synonym for the ack. The tool descriptor alone cannot carry that: it
        // is read at call time, and the choice is made before the call.
        for (role, name) in [(BRIAN_ROLE, "BRIAN_ROLE"), (RAIN_ROLE, "RAIN_ROLE")] {
            assert!(role.contains("pass_turn"), "{name} must document pass_turn");
            assert!(
                role.contains("counts toward nothing"),
                "{name} must say a pass does not count toward the session settling"
            );
        }
    }

    #[test]
    fn rain_forbids_state_transition_relays() {
        // Regression guard for the #374 session observation: Rain emitted
        // "User approved. Go ahead, Brian.", "Standing by for the test
        // results", "Review complete." — heartbeat-style relays of state
        // changes Brian could see directly. The prompt must specifically
        // forbid that class of message, not just the "Holding." variant.
        assert!(RAIN_ROLE.contains("Silent on state transitions"));
        assert!(RAIN_ROLE.contains("Brian reads the same"));
    }

    #[test]
    fn brian_teaches_question_introspection() {
        // Retry-duplicate antipattern: on ask_user_choice timeout, Brian
        // would just re-call ask_user_choice repeatedly, accumulating
        // identical pending choices in the tray. Prompt must point him at
        // list_my_pending_questions / withdraw_question before re-asking.
        assert!(BRIAN_ROLE.contains("list_my_pending_questions"));
        assert!(BRIAN_ROLE.contains("withdraw_question"));
    }

    #[test]
    fn brian_distinguishes_halt_from_close_ask() {
        // Today's session showed Brian calling mark_awaiting_user after
        // settled work instead of ask_user_choice("Close session?", ...).
        // The session lingered and accumulated stale questions. The prompt
        // must explicitly contrast halt (mid-task pause) vs close-ask
        // (end-of-task), not just mention both.
        assert!(BRIAN_ROLE.contains("Halt is for mid-task pauses"));
        assert!(BRIAN_ROLE.contains("close-ask is for end-of-task"));
    }

    #[test]
    fn brian_handles_ambiguous_resume_words() {
        // Today's session: user typed "proceed" with multiple plausible
        // threads in flight. Brian inferred scope from current working-tree
        // state and missed the prior task framing. Prompt must teach the
        // ask-with-prior-context move for bare resume words.
        assert!(BRIAN_ROLE.contains("Ambiguous resume words"));
        assert!(BRIAN_ROLE.contains("ambiguity → ask, single thread → resume"));
    }

    #[test]
    fn rain_web_search_guidance_is_conditional_not_blanket() {
        // June-6 #5: the old "Prefer web_search for live lookups" was vague
        // and read as "always search." Sharpened to when-to-search: only when
        // the question reaches outside the repo. Lock the conditional framing
        // and guard against drifting back to the blanket "prefer" wording.
        assert!(
            RAIN_ROLE.contains("Reach for `web_search` when the question reaches OUTSIDE the repo"),
            "Rain web_search guidance must be scoped to external questions"
        );
        assert!(
            RAIN_ROLE.contains("Skip it for codebase-internal questions"),
            "Rain must be told to skip web_search for codebase-internal questions"
        );
        assert!(
            !RAIN_ROLE.contains("Prefer `web_search` for live lookups"),
            "the vague blanket 'prefer' wording must not return"
        );
    }

    #[test]
    fn both_duo_roles_have_session_opener() {
        // Issue #378 (acme-app) shipped with partial-formatter pollution
        // because neither Brian nor Rain called cl_index_search at session
        // start — they jumped straight to `gh issue view` + `grep` and
        // missed the project's documented formatter convention. Both
        // role prompts must explicitly demand cl_index_search as the FIRST
        // tool call, not bury it as a tip.
        assert!(BRIAN_ROLE.contains("Session opener"));
        assert!(BRIAN_ROLE.contains("cl_index_search"));
        assert!(RAIN_ROLE.contains("Session opener"));
        assert!(RAIN_ROLE.contains("cl_index_search"));
    }

    #[test]
    fn brian_owns_one_rewritable_doc_per_phase_and_chains() {
        // The CL/IPAV tightening: Brian authors ONE rewritable doc per phase
        // (no plan-v2), and each phase builds on the prior phase's doc.
        assert!(BRIAN_ROLE.contains("One doc per phase"));
        assert!(BRIAN_ROLE.contains("You (HANDS) author the phase docs"));
        assert!(BRIAN_ROLE.contains("Each phase builds on the last"));
        assert!(BRIAN_ROLE.contains("The `apply` doc is the deliverable"));
    }

    #[test]
    fn rain_reviews_brian_output_bottom_up() {
        // June-3 idea, sharpened by the 2026-06-16 duo-survey convergence:
        // Rain reads BOTTOM-UP (tests → error paths → callers → impl →
        // architecture), the inverse of Brian's top-down — but as a REVIEW
        // LENS on what Brian produced, not a parallel from-scratch
        // investigation that re-derives his findings (the producer/producer
        // waste both duos flagged). Still names the leaf-first order and
        // requires convergence.
        assert!(RAIN_ROLE.contains("Bottom-up review"));
        assert!(RAIN_ROLE.contains("the opposite direction from Brian"));
        assert!(RAIN_ROLE.contains("tests"));
        assert!(RAIN_ROLE.contains("converge"));
        assert!(RAIN_ROLE.contains("a review lens, not a parallel investigation"));
    }

    #[test]
    fn rain_verifies_brian_output_not_parallel_rederive() {
        // 2026-06-16 duo-survey #2 (converged across both duos): EYES
        // re-deriving the same findings as HANDS in parallel is waste. Rain's
        // primary job is to VERIFY Brian's outputs (plan/diff/conclusions),
        // reading them before producing her own — one producer + one
        // adversarial reviewer, not two parallel producers.
        assert!(RAIN_ROLE.contains("Your highest-value job is to verify what Brian PRODUCES"));
        assert!(RAIN_ROLE.contains("Read Brian's output before you produce your own"));
        assert!(RAIN_ROLE.contains("two parallel producers"));
    }

    #[test]
    fn rain_resyncs_from_tree_before_review() {
        // Rain can't see Brian's tool calls (Edit/Bash/Read) through the peer
        // channel — only prose, and nothing during an awaiting-halt. So before
        // reviewing she re-syncs from source of truth: the apply doc first
        // (HANDS-authored, repo-independent), then git. Never conclude "nothing
        // landed" from peer-stream silence (the 2026-06-04 desync).
        assert!(RAIN_ROLE.contains("Re-sync from the tree"));
        assert!(RAIN_ROLE.contains("session_doc_search(phase=\"apply\")"));
        assert!(RAIN_ROLE.contains("git status --short"));
        assert!(RAIN_ROLE.contains("from peer-stream silence"));
    }

    #[test]
    fn rain_contributes_to_co_located_eyes_phase_doc() {
        // 2026-06-16 duo-survey: EYES gets a durable voice in the phase tab
        // WITHOUT clobbering Brian's doc — a phase-tagged write from Rain lands
        // in a co-located `<phase>-eyes` doc, not Brian's single per-phase doc.
        // The prompt must tell her this so she uses it instead of only chat.
        assert!(RAIN_ROLE.contains("you can't clobber Brian's"));
        assert!(RAIN_ROLE.contains("<phase>-eyes"));
        assert!(!RAIN_ROLE.contains("Don't write phase-tagged session docs"));
    }

    #[test]
    fn brian_writes_cl_delta_before_close() {
        // Write-the-delta close loop: Brian writes a bounded learnings delta
        // to the CL (cl_write_file) before close_session kills the subprocess.
        assert!(BRIAN_ROLE.contains(
            "write your bounded CL learnings delta via `cl_write_file` BEFORE calling `close_session`"
        ));
    }
}

