//! Strip the AppImage runtime's environment out of the processes bot-hq
//! spawns.
//!
//! # The bug this closes
//!
//! A Linux AppImage launches through `AppRun`, which exports a payload-rooted
//! environment so the bundled app can find its own libraries: `LD_LIBRARY_PATH`,
//! `PATH`, `PYTHONHOME`, `PYTHONPATH`, `PERLLIB`, `QT_PLUGIN_PATH`,
//! `XDG_DATA_DIRS`, the `GTK_*`/`GIO_*`/`GST_*`/`GSETTINGS_*` family, and
//! `APPDIR` itself. Every child bot-hq spawns inherits that wholesale — and a
//! child is usually a HOST binary, which then loads the payload's
//! Ubuntu-22.04-era libraries instead of its own.
//!
//! Measured on Fedora 44 (2026-08-25), inside a live session:
//!
//! - `git` over HTTPS dies — `git-remote-https: symbol lookup error:
//!   /lib64/libcurl.so.4: undefined symbol:
//!   nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation`. Fetch,
//!   pull and push are all unavailable to an agent, and the `pre-push` hook
//!   never gets to render a verdict because the transport is already gone.
//! - `curl` dies with the identical error (`ldd /lib64/libcurl.so.4` resolves
//!   twelve dependencies into the payload — the whole HTTP/TLS/Kerberos chain).
//! - `python3` dies: `Fatal Python error: Failed to import encodings module`,
//!   because `PYTHONHOME` points at a payload prefix with no python lib dir.
//! - `flatpak` dies in the session's own Terminal tab.
//! - `gsettings` LIES rather than dying — and not by the mechanism it first
//!   appears to. `LD_LIBRARY_PATH` makes host `gsettings` load the PAYLOAD's
//!   glib/gio, whose module directory ships only `libgiognutls.so` where the
//!   host has `libdconfsettings.so`. With no dconf backend, every key returns
//!   its SCHEMA DEFAULT: `'Adwaita'`/`'default'` where the host really says
//!   `'Breeze'`/`'prefer-dark'`. Measured — unsetting `GSETTINGS_SCHEMA_DIR`
//!   or `GIO_EXTRA_MODULES` changes nothing; unsetting `LD_LIBRARY_PATH`
//!   restores the truth. The schema-shadowing theory was wrong and nearly
//!   produced a false correction against a correct diagnosis.
//!
//! # Why the fix lives here and not in `AppRun`
//!
//! Unsetting these in the launcher would strip the payload libraries from
//! `WebKitWebProcess` too, which genuinely needs them — that is the
//! `EGL_BAD_PARAMETER` no-window failure `docs/FEDORA-LINUX-COMPAT.md`
//! documents. The app keeps the AppImage environment; only what it SPAWNS is
//! scrubbed.
//!
//! # Why a structural rule and not a list of variable names
//!
//! `AppRun` is generated by linuxdeploy and can add variables at any release.
//! A name blocklist would silently go stale. The rule here is instead:
//!
//! > For every inherited variable, treat the value as a `:`-separated list,
//! > drop every entry that resolves under `$APPDIR`, and remove the variable
//! > entirely if nothing survives.
//!
//! Two exceptions, both learned in review:
//!
//! 1. **`PATH` is never removed** — a child with no `PATH` cannot resolve a
//!    bare command name at all. If every entry was payload-rooted it falls back
//!    to [`PATH_FALLBACK`].
//! 2. **If nothing was dropped, nothing is emitted.** Not `Set(name, rejoin)` —
//!    no op at all. Rejoining is not byte-identical for values this rule was
//!    never meant to touch: `LD_LIBRARY_PATH` and `GST_PLUGIN_SYSTEM_PATH_1_0`
//!    carry a trailing `:`, and `DEBUGINFOD_URLS` is space-separated with
//!    embedded colons. Emitting nothing makes the no-op case exact by
//!    construction rather than by luck.

use std::path::{Path, PathBuf};

/// What to do with one inherited variable. Applied by the `scrub_*` helpers.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EnvOp {
    /// Unset it in the child.
    Remove(String),
    /// Replace it with the surviving entries.
    Set(String, String),
}

/// Where `PATH` lands if every one of its entries was payload-rooted. POSIX
/// minimum; a child with no `PATH` cannot resolve `git` or `sh` at all.
pub const PATH_FALLBACK: &str = "/usr/bin:/bin";

/// The decision, as a pure function over the inherited environment.
///
/// Order is preserved and only affected variables produce an op — see the
/// module docs for the two exceptions.
pub fn scrub<I, K, V>(vars: I, appdir: &Path) -> Vec<EnvOp>
where
    I: IntoIterator<Item = (K, V)>,
    K: AsRef<str>,
    V: AsRef<str>,
{
    let mut ops = Vec::new();
    for (name, value) in vars {
        let (name, value) = (name.as_ref(), value.as_ref());
        let entries: Vec<&str> = value.split(':').collect();
        if !entries.iter().any(|entry| is_under(entry, appdir)) {
            // Nothing payload-rooted. Emit NOTHING, so a value this rule was
            // never meant to touch is not round-tripped through split/join.
            continue;
        }
        // Empty segments are dropped only once we know we are rewriting this
        // variable anyway. Keeping them would be a real bug: six live vars
        // (LD_LIBRARY_PATH, PYTHONPATH, PERLLIB, QT_PLUGIN_PATH and both
        // GST_PLUGIN_SYSTEM_PATH forms) end in a trailing `:`, so an
        // all-payload value leaves `kept == [""]` — not empty — and the var
        // would be SET to "" instead of removed. For PATH that is the
        // difference between the fallback below and a child that cannot
        // resolve `sh` at all.
        let kept: Vec<&str> = entries
            .iter()
            .copied()
            .filter(|entry| !is_under(entry, appdir) && !entry.is_empty())
            .collect();
        if kept.is_empty() {
            if name == "PATH" {
                ops.push(EnvOp::Set(name.to_string(), PATH_FALLBACK.to_string()));
            } else {
                ops.push(EnvOp::Remove(name.to_string()));
            }
            continue;
        }
        ops.push(EnvOp::Set(name.to_string(), kept.join(":")));
    }
    ops
}

/// Is one `:`-separated entry inside the AppImage payload?
///
/// Component-wise rather than string-prefix, so the `$APPDIR//usr/lib` double
/// slashes `AppRun` emits still match, and so `/home/x/squashfs-root-notmine`
/// does NOT match `/home/x/squashfs-root`.
fn is_under(entry: &str, appdir: &Path) -> bool {
    !entry.is_empty() && Path::new(entry).starts_with(appdir)
}

/// The payload root, when this process is genuinely running from one.
///
/// `None` — so every `scrub_*` helper is a strict no-op — unless all three
/// hold: this is Linux, `APPDIR` is set and non-empty, and our own executable
/// lives under it. The last check is what keeps a developer's own `APPDIR`
/// (or a stale one inherited from some other AppImage) from causing bot-hq to
/// strip environment it never injected.
pub fn payload_root() -> Option<PathBuf> {
    if !cfg!(target_os = "linux") {
        return None;
    }
    let appdir = std::env::var_os("APPDIR").filter(|v| !v.is_empty())?;
    let appdir = PathBuf::from(appdir);
    let exe = std::env::current_exe().ok()?;
    exe.starts_with(&appdir).then_some(appdir)
}

/// Ops for the current process's environment, or empty when not under a
/// payload.
fn ops_for_current_env() -> Vec<EnvOp> {
    let Some(appdir) = payload_root() else {
        return Vec::new();
    };
    // `vars_os` + filter, never `vars()`: that one PANICS on a non-UTF-8
    // variable, and this runs on every agent spawn, Terminal spawn, gated
    // command and library push — a panic here would take out the spawn path,
    // not merely the scrub. A non-UTF-8 variable is left exactly as inherited;
    // rewriting one lossily would corrupt it.
    let vars: Vec<(String, String)> = std::env::vars_os()
        .filter_map(|(k, v)| Some((k.into_string().ok()?, v.into_string().ok()?)))
        .collect();
    scrub(vars, &appdir)
}

/// Apply to a [`std::process::Command`].
pub fn scrub_std(cmd: &mut std::process::Command) {
    for op in ops_for_current_env() {
        match op {
            EnvOp::Remove(name) => {
                cmd.env_remove(name);
            }
            EnvOp::Set(name, value) => {
                cmd.env(name, value);
            }
        }
    }
}

/// Apply to a [`tokio::process::Command`] — the gated-command runner.
pub fn scrub_tokio(cmd: &mut tokio::process::Command) {
    for op in ops_for_current_env() {
        match op {
            EnvOp::Remove(name) => {
                cmd.env_remove(name);
            }
            EnvOp::Set(name, value) => {
                cmd.env(name, value);
            }
        }
    }
}

/// Apply to a `portable_pty` [`CommandBuilder`] — the session Terminal.
pub fn scrub_pty(cmd: &mut portable_pty::CommandBuilder) {
    for op in ops_for_current_env() {
        match op {
            // A real unset, not an empty value: an empty `LD_LIBRARY_PATH`
            // is not the same as no `LD_LIBRARY_PATH` to every loader.
            EnvOp::Remove(name) => cmd.env_remove(name),
            EnvOp::Set(name, value) => cmd.env(name, value),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const APPDIR: &str = "/home/u/.local/lib/bot-hq/squashfs-root";

    fn ops(vars: &[(&str, &str)]) -> Vec<EnvOp> {
        scrub(vars.iter().copied(), Path::new(APPDIR))
    }

    #[test]
    fn drops_an_all_payload_variable() {
        // LD_LIBRARY_PATH is the one that breaks host git and curl.
        let v = format!("{APPDIR}/usr/lib/:{APPDIR}/usr/lib/x86_64-linux-gnu/");
        assert_eq!(
            ops(&[("LD_LIBRARY_PATH", &v)]),
            vec![EnvOp::Remove("LD_LIBRARY_PATH".into())]
        );
    }

    #[test]
    fn keeps_host_entries_and_drops_payload_ones() {
        let v = format!("{APPDIR}/usr/share/:/usr/share:/usr/local/share");
        assert_eq!(
            ops(&[("XDG_DATA_DIRS", &v)]),
            vec![EnvOp::Set(
                "XDG_DATA_DIRS".into(),
                "/usr/share:/usr/local/share".into()
            )]
        );
    }

    #[test]
    fn path_is_never_removed_even_when_fully_payload_rooted() {
        // A child with no PATH cannot resolve `git` or `sh`.
        let v = format!("{APPDIR}/usr/bin/:{APPDIR}/usr/sbin/");
        assert_eq!(
            ops(&[("PATH", &v)]),
            vec![EnvOp::Set("PATH".into(), PATH_FALLBACK.into())]
        );
    }

    #[test]
    fn path_keeps_its_host_entries_when_it_has_them() {
        let v = format!("{APPDIR}/usr/bin/:/usr/bin:/bin");
        assert_eq!(
            ops(&[("PATH", &v)]),
            vec![EnvOp::Set("PATH".into(), "/usr/bin:/bin".into())]
        );
    }

    #[test]
    fn nothing_dropped_emits_no_op_at_all() {
        // The byte-identity rule. A trailing separator and a space-separated
        // value with embedded colons must survive untouched — emitting
        // Set(name, rejoined) would rewrite both.
        assert_eq!(
            ops(&[
                ("GDK_BACKEND", "x11"),
                ("GTK_THEME", "Adwaita:light"),
                ("DEBUGINFOD_URLS", "ima:enforcing https://x.example ima:ignore "),
                ("SOME_LIST", "/usr/lib:/usr/local/lib:"),
            ]),
            vec![]
        );
    }

    #[test]
    fn single_valued_payload_variables_are_removed() {
        // PYTHONHOME is the one that makes python3 fail to import encodings.
        let home = format!("{APPDIR}/usr/");
        let cache = format!("{APPDIR}//usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache");
        assert_eq!(
            ops(&[("PYTHONHOME", &home), ("GDK_PIXBUF_MODULE_FILE", &cache)]),
            vec![
                EnvOp::Remove("PYTHONHOME".into()),
                EnvOp::Remove("GDK_PIXBUF_MODULE_FILE".into()),
            ]
        );
    }

    #[test]
    fn appdir_itself_is_removed() {
        assert_eq!(
            ops(&[("APPDIR", APPDIR)]),
            vec![EnvOp::Remove("APPDIR".into())]
        );
    }

    #[test]
    fn a_sibling_path_that_merely_shares_a_prefix_is_kept() {
        // String-prefix matching would eat this one.
        let v = format!("{APPDIR}-backup/usr/lib:/usr/lib");
        assert_eq!(ops(&[("LD_LIBRARY_PATH", &v)]), vec![]);
    }

    #[test]
    fn a_trailing_separator_does_not_keep_an_all_payload_var_alive() {
        // Six live vars ship a trailing `:`. Before the empty-segment filter
        // this produced Set(name, "") — the exact thing `scrub_pty`'s comment
        // warns against — instead of Remove.
        let v = format!("{APPDIR}/usr/lib/:{APPDIR}/usr/lib/x86_64-linux-gnu/:");
        assert_eq!(
            ops(&[("LD_LIBRARY_PATH", &v)]),
            vec![EnvOp::Remove("LD_LIBRARY_PATH".into())]
        );
    }

    #[test]
    fn a_trailing_separator_does_not_bypass_the_path_fallback() {
        // The sharp edge: Set("PATH", "") makes a child unable to resolve any
        // bare command — `env PATH= sh -c ...` cannot even find `sh`.
        let v = format!("{APPDIR}/usr/bin/:");
        assert_eq!(
            ops(&[("PATH", &v)]),
            vec![EnvOp::Set("PATH".into(), PATH_FALLBACK.into())]
        );
    }

    #[test]
    fn empty_segments_are_dropped_only_when_the_var_is_rewritten_anyway() {
        let v = format!("{APPDIR}/usr/lib:/usr/lib:");
        assert_eq!(
            ops(&[("LD_LIBRARY_PATH", &v)]),
            vec![EnvOp::Set("LD_LIBRARY_PATH".into(), "/usr/lib".into())]
        );
    }

    #[test]
    fn an_empty_environment_produces_nothing() {
        assert_eq!(ops(&[]), vec![]);
    }

    #[test]
    fn order_is_preserved() {
        let v = format!("{APPDIR}/a");
        let ops = ops(&[("Z_FIRST", &v), ("A_SECOND", &v)]);
        assert_eq!(
            ops,
            vec![
                EnvOp::Remove("Z_FIRST".into()),
                EnvOp::Remove("A_SECOND".into())
            ]
        );
    }
}
