// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async createSession(id: string, title: string, repoPath: string | null, project: string | null) : Promise<Result<SessionInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_session", { id, title, repoPath, project }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSession(sessionId: string) : Promise<Result<SessionInfo | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSessions() : Promise<Result<SessionInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_sessions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spawn (or re-spawn) the agent subprocesses for an existing session row.
 * Idempotent — `core::AppState::ensure_session_started` is a no-op if the
 * session is already live. Mirrors the Slint-era click-to-respawn flow:
 * frontend SessionView calls this on mount so a reopened bot-hq window
 * brings Brian + Rain back via `claude --resume <uuid>`.
 */
async respawnSession(sessionId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("respawn_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the current IPAV phase for a session. Returns one of "investigate" /
 * "plan" / "apply" / "verify", or `None` if the session isn't live (IPAV
 * state is in-memory only — restart loses it). Frontend SessionView header
 * uses this for the initial phase chip; subsequent updates come from the
 * `session:phase_changed` Tauri event.
 */
async getSessionPhase(sessionId: string) : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session_phase", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Advance the IPAV phase from the UI. Target accepts single-letter chips
 * (`I`/`P`/`A`/`V`) or full names (`Investigate`/`Plan`/`Apply`/`Verify`).
 * Synthesizes a phase-change message in storage + feeds the transition
 * notice to both agents' stdin so they pick up the new phase as a prompt.
 */
async advanceSessionPhase(sessionId: string, target: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("advance_session_phase", { sessionId, target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeSession(sessionId: string, archive: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_session", { sessionId, archive }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSessionMessages(sessionId: string, sinceId: number | null) : Promise<Result<AgentMessage[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session_messages", { sessionId, sinceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a user message to a session. For the duo session this fans out to
 * both Brian and Rain (with phase envelope); for Emma's solo session it
 * goes to her singleton agent. Persists the raw text + notifies the bridge.
 */
async broadcastMessage(sessionId: string, text: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("broadcast_message", { sessionId, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAgentConfig(agentName: string) : Promise<Result<AgentConfigView | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_agent_config", { agentName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAgentConfigs() : Promise<Result<AgentConfigView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_agent_configs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertAgentConfig(cfg: AgentConfigView) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_agent_config", { cfg }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clIndexSearch(project: string | null, query: string | null) : Promise<Result<ClIndexEntryView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_index_search", { project, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clFolderSearch(project: string | null, query: string | null) : Promise<Result<ClFolderView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_folder_search", { project, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clRegisterRead(agent: string, sessionId: string | null, project: string, filePath: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_register_read", { agent, sessionId, project, filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clRescan(project: string) : Promise<Result<ClRescanReportView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_rescan", { project }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProjects() : Promise<Result<ProjectView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a single CL file's contents, resolved as
 * `<data_dir>/projects/<project>/<file_path>`. Hard cap on read size so a
 * very large file can't pin the IPC. Path-traversal guarded by
 * canonicalizing both the project root and the resolved file and
 * rejecting any read that escapes.
 */
async clReadFile(project: string, filePath: string) : Promise<Result<ClFileContentView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_read_file", { project, filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the description (and optionally tags) on a CL index entry. Used by
 * the ContextLibrary UI's inline edit flow. Underlying call is the same
 * idempotent `upsert_cl_index` the backfill scan uses, so calling on an
 * entry that doesn't exist yet is fine — it creates the row.
 */
async clSetDescription(project: string, filePath: string, description: string, tags: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_set_description", { project, filePath, description, tags }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async grantSessionPermission(sessionId: string, action: PermissionActionView, scope: GrantScopeView) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grant_session_permission", { sessionId, action, scope }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async revokeSessionPermission(sessionId: string, action: PermissionActionView) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("revoke_session_permission", { sessionId, action }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSessionPermissions(sessionId: string) : Promise<Result<SessionPermissionsView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_session_permissions", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPendingChoices() : Promise<Result<PendingChoiceView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_pending_choices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveChoice(choiceId: string, picked: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_choice", { choiceId, picked }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionDocSearch(sessionId: string, query: string | null, phase: string | null) : Promise<Result<SessionDocumentView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_doc_search", { sessionId, query, phase }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionDocRead(sessionId: string, slug: string) : Promise<Result<SessionDocumentView | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_doc_read", { sessionId, slug }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `git diff --no-color <session_start_sha>` (falling back to
 * `git diff HEAD` if the anchor was never captured) inside the session's
 * `working_repo_path`, then classify each line via [`parse_diff_lines`].
 * 
 * Returns an empty `lines` Vec with a note if the diff is empty, the
 * session isn't running, or the session has no working repo. Errors only
 * when the git invocation itself can't be spawned.
 */
async computeApplyDiff(sessionId: string) : Promise<Result<ComputeApplyDiffResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("compute_apply_diff", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async captureWindowScreenshot(sessionId: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("capture_window_screenshot", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AgentConfigView = { agent_name: string; provider: string; model_name: string; base_url: string | null; auth_token: string | null; updated_at: string }
/**
 * One chat message in the chronological stream. Mirrors `storage::Message`
 * with `created_at` left as a string (ISO) so the frontend can parse with
 * whatever date library it picks.
 */
export type AgentMessage = { id: number; session_id: string; author: string; kind: string; content: string; created_at: string }
export type AppError = 
/**
 * Bad input. Frontend should highlight the offending field if it knows
 * which one. Otherwise a toast.
 */
{ kind: "Validation"; message: string } | 
/**
 * Resource doesn't exist (404-ish). Frontend can redirect or show empty
 * state.
 */
{ kind: "NotFound"; message: string } | 
/**
 * Authentication / authorization failure (e.g., trying to call a HANDS-
 * only tool from EYES, or a plugin missing a capability grant).
 */
{ kind: "Unauthorized"; message: string } | 
/**
 * Unexpected error not classified elsewhere. Toast with the message.
 */
{ kind: "Internal"; message: string } | 
/**
 * Sqlite write/read failure. Toast + log + offer retry.
 */
{ kind: "DbError"; message: string } | 
/**
 * Tauri capability check denied a plugin's request.
 */
{ kind: "CapabilityDenied"; message: string }
export type ClFileContentView = { project: string; file_path: string; content: string; 
/**
 * Byte size of the file as it lives on disk. The `content` field is
 * the full text — included as a sanity check for the frontend.
 */
size_bytes: number; 
/**
 * True when the file was truncated because it exceeded the read cap.
 * Frontend can show a "showing first 1 MB" notice and offer to open
 * in $EDITOR (deferred).
 */
truncated: boolean }
export type ClFolderView = { id: number; project_id: string; folder_path: string; description: string; tags: string | null; created_at: string; updated_at: string }
export type ClIndexEntryView = { id: number; project_id: string; file_path: string; description: string; tags: string | null; created_at: string; updated_at: string }
export type ClRescanReportView = { added: string[]; touched: string[]; orphaned: string[] }
/**
 * Result of `compute_apply_diff`: the classified diff lines plus an
 * optional human-readable note (e.g., the session-start anchor was lost
 * and we fell back to `git diff HEAD`).
 */
export type ComputeApplyDiffResult = { lines: DiffLine[]; note: string | null }
/**
 * One classified line of a unified `git diff`. Ports the Slint-era
 * `DiffLine` struct (deleted with `view_model.rs`). `kind` is one of
 * `"add" | "remove" | "hunk" | "file" | "context"` — order-sensitive
 * classification per [`parse_diff_lines`].
 */
export type DiffLine = { kind: string; text: string }
export type GrantScopeView = { kind: "none" } | { kind: "all_branches" } | { kind: "specific"; branches: string[] }
export type PendingChoiceView = { choice_id: string; session_id: string; agent: string; question: string; options: string[] }
export type PermissionActionView = "commit" | "push"
/**
 * Project as exposed to the frontend. Drives the project-filter dropdown
 * in ContextLibrary and (eventually) the New-Session repo picker.
 */
export type ProjectView = { name: string; display_name: string; working_repo_path: string | null; description: string | null }
export type SessionDocumentView = { id: number; session_id: string; slug: string; body: string; created_at: string; updated_at: string; phase: string | null }
export type SessionInfo = { id: string; title: string; working_repo_path: string | null; archived: boolean; created_at: string; closed_at: string | null; brian_model_at_spawn: string | null; rain_model_at_spawn: string | null }
export type SessionPermissionsView = { commit: GrantScopeView; push: GrantScopeView }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
