// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async createSession(id: string, title: string, repoPath: string | null, project: string | null, rainEnabled: boolean | null, brianModelId: string | null, rainModelId: string | null, options: SessionCreateOptions) : Promise<Result<SessionInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_session", { id, title, repoPath, project, rainEnabled, brianModelId, rainModelId, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dispatch a session pre-loaded with a first prompt: create the row, register
 * the project, spawn the duo, and broadcast `prompt` to their stdin — all in
 * one call so delivery is deterministic. A fresh session spawns blank
 * (`resume_session_id = None`) and bot-hq does NOT replay storage to stdin, so
 * the prompt has to be broadcast to a LIVE session — which means spawning
 * first. `ensure_session_started` inserts the handle before returning, so the
 * subsequent `broadcast` always finds it; it's idempotent, so the SessionView
 * mount's `respawn_session` is a harmless no-op.
 * 
 * Generic on purpose — the caller supplies the prompt. The Context Library
 * "Maintain CL" button calls this with a hardcoded CL-maintenance prompt.
 */
async dispatchSession(id: string, title: string, project: string | null, repoPath: string | null, prompt: string) : Promise<Result<SessionInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dispatch_session", { id, title, project, repoPath, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSession(sessionId: string) : Promise<Result<SessionInfo | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSessionRuntime() : Promise<Result<SessionRuntime[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session_runtime") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve a session's project + how it was derived, so the gear tab can show
 * WHY the session inherited its policy (registered repo vs path basename vs
 * no project → general). Deterministic from the session's repo paths — no
 * persisted column needed.
 */
async getSessionProjectInfo(sessionId: string) : Promise<Result<SessionProjectInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session_project_info", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkSessionDirty(sessionId: string) : Promise<Result<SessionDirty, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_session_dirty", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * C1: the kept-worktree path for a closed worktree-session, if its isolated
 * worktree still exists on disk. `close_session` keeps (never force-removes) a
 * dirty worktree, so its presence after close ⇒ uncommitted work was left
 * there. `None` for a direct-mode session or a clean worktree that was removed.
 * Lets the Archive surface "work was kept here" for recovery.
 */
async sessionWorktreeKept(sessionId: string) : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_worktree_kept", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSessions() : Promise<Result<SessionInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_sessions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * All closed sessions (just-closed + archived), most-recently-closed first.
 * Backs the Settings → Archive tab.
 */
async listClosedSessions() : Promise<Result<SessionInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_closed_sessions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spawn (or re-spawn) the agent subprocesses for an existing session row.
 * Idempotent — `core::AppState::ensure_session_started` is a no-op if the
 * session is already live. Mirrors the click-to-respawn flow:
 * frontend SessionView calls this on mount so a reopened bot-hq window
 * brings Brian + Rain back via `claude --resume <uuid>`.
 */
async respawnSession(sessionId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("respawn_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Force-restart a live session's agents so they pick up a Claude-config change
 * (overrides + inherited settings are read at spawn). Unlike `respawn_session`
 * this is NOT a no-op on a healthy session — it evicts and re-spawns. Agents
 * resume their prior conversation via `--resume`.
 */
async restartSession(sessionId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restart_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel a session's in-flight turn (the Stop button — interrupt redesign,
 * Batch 3 + 3.1, now interrupt-first). Sends a `control_request` interrupt to
 * abort the turn while KEEPING the process alive (warm cache, no `--resume`
 * respawn); if an agent doesn't honor it within ~2s it's SIGKILLed as a
 * fallback. The session returns to `Idle` (the chat input unlocks). If HANDS is
 * mid an atomic op (`git commit`/`git push`/migration), the interrupt is
 * DEFERRED until the op completes (≤ ~8s cap) so the working tree isn't left
 * half-written. The command returns immediately and a detached task drives the
 * escalation. No-op if the session isn't live.
 */
async cancelSessionTurn(sessionId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_session_turn", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename a session (inline edit in the SessionView header). Blank titles are
 * rejected — an empty header is indistinguishable from a render bug.
 */
async renameSession(sessionId: string, title: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_session", { sessionId, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the current IPAV phase for a session. Returns one of "investigate" /
 * "plan" / "apply" / "verify", or `None` if the session isn't live (IPAV
 * state is in-memory only — restart loses it). Frontend SessionView header
 * uses this for the initial phase chip; subsequent updates come from the
 * `session:phase_changed` Tauri event.
 */
async getSessionPhase(sessionId: string) : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session_phase", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Close a session from the UI. Delegates to `core.close_session`, which is
 * the single source of truth for closing: it removes the live handle, KILLS
 * the brian/rain subprocesses, and marks the row closed/archived in storage.
 * The previous version called `storage.close_session` directly, so it set
 * `closed_at` but left the subprocesses running — a session that "closed" in
 * the DB yet kept taking turns. Routing through core fixes that.
 */
async closeSession(sessionId: string, archive: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_session", { sessionId, archive }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSessionMessages(sessionId: string, sinceId: number | null) : Promise<Result<AgentMessage[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session_messages", { sessionId, sinceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a user message to a session. For the duo session this fans out to
 * both Brian and Rain (with phase envelope). Persists the raw text + notifies the bridge.
 */
async broadcastMessage(sessionId: string, text: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("broadcast_message", { sessionId, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAgentConfig(agentName: string) : Promise<Result<AgentConfigView | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_agent_config", { agentName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAgentConfigs() : Promise<Result<AgentConfigView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_agent_configs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertAgentConfig(cfg: AgentConfigView) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_agent_config", { cfg }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listModels() : Promise<Result<ModelView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertModel(model: ModelView) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_model", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModel(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSetting(key: string) : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAppSetting(key: string, value: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_app_setting", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clIndexSearch(project: string | null, query: string | null) : Promise<Result<ClIndexEntryView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_index_search", { project, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clFolderSearch(project: string | null, query: string | null) : Promise<Result<ClFolderView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_folder_search", { project, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clRescan(project: string) : Promise<Result<ClRescanReportView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_rescan", { project }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clListProposals(project: string, status: string | null) : Promise<Result<ClProposalView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_list_proposals", { project, status }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open-proposal counts per project in one call — feeds the Context Manager
 * sidebar badges and the subtab pill's cross-project sum. Kept fresh by the
 * `cl:proposals_changed` event (filing/rejection are DB-only writes the CL
 * fs-watcher can't see).
 */
async clProposalCounts() : Promise<Result<ClProposalCountView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_proposal_counts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clApproveProposal(proposalUid: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_approve_proposal", { proposalUid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clRejectProposal(proposalUid: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_reject_proposal", { proposalUid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read-side telemetry for the Library measurement card. `project` scopes to one
 * CL project (None = all); `since` is an RFC3339 lower bound on `created_at`
 * (None = all time).
 */
async clRetrievalStats(project: string | null, since: string | null) : Promise<Result<RetrievalStatsView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_retrieval_stats", { project, since }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProjects() : Promise<Result<ProjectView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a single CL file's contents, resolved as
 * `<data_dir>/projects/<project>/<file_path>`. Hard cap on read size so a
 * very large file can't pin the IPC. Path-traversal guarded by
 * canonicalizing both the project root and the resolved file and
 * rejecting any read that escapes.
 */
async clReadFile(project: string, filePath: string) : Promise<Result<ClFileContentView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_read_file", { project, filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Overwrite an existing CL file's contents, resolved exactly like
 * [`cl_read_file`] (same `cl_project_root` + path-traversal guard via
 * [`resolve_existing_cl_file`]). Edits existing regular files only —
 * creating new files / directories are separate commands. `content` is
 * written as UTF-8 bytes; the editor is responsible for not saving a file
 * it flagged `binary` or `truncated` (either would lose data).
 */
async clWriteFile(project: string, filePath: string, content: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_write_file", { project, filePath, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the description (and optionally tags) on a CL index entry. Used by
 * the ContextLibrary UI's inline edit flow. Underlying call is the same
 * idempotent `upsert_cl_index` the backfill scan uses, so calling on an
 * entry that doesn't exist yet is fine — it creates the row.
 */
async clSetDescription(project: string, filePath: string, description: string, tags: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_set_description", { project, filePath, description, tags }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Upsert a folder's description + tags (`cl_folders`). Used by the Context
 * Library folder-view editor. Routes through the bridge helper so the project
 * row is ensured to exist first (same path as the agent-facing
 * `cl_register_folder_description` MCP tool). `folder_path = ""` is the
 * project-root folder's description.
 */
async clSetFolderDescription(project: string, folderPath: string, description: string, tags: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_set_folder_description", { project, folderPath, description, tags }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a folder's description row. The folder itself stays in the tree
 * (it's still on disk); only the CL annotation is removed.
 */
async clDeleteFolderDescription(project: string, folderPath: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_delete_folder_description", { project, folderPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Register a project, or update an existing one. Used by the Context Library
 * to promote an arbitrary on-disk folder to a project (`cl_path` = that
 * folder) and to edit an existing project's working-repo from the folder-view.
 * `upsert_project` COALESCEs `None` fields, so passing only the values you
 * want to change preserves the rest. When `cl_path` is supplied it must point
 * at a real directory (guards against registering a typo'd path).
 */
async clRegisterProject(name: string, displayName: string | null, workingRepoPath: string | null, clPath: string | null, description: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_register_project", { name, displayName, workingRepoPath, clPath, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Soft-unregister a project: clears `cl_path` + `working_repo_path` but KEEPS
 * the row and all child CL rows (index, folders, reads). The project stops
 * being a usable session target; its descriptions survive for re-registration.
 */
async clUnregisterProject(name: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_unregister_project", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a NEW Context Library project at the default managed location
 * (`<data_dir>/library/projects/<name>/`). Unlike [`cl_register_project`] this
 * NEVER sets `cl_path` and NEVER indexes an external folder — it makes the
 * convention dir, seeds starter `conventions.md` + `notes.md` (if absent), and
 * rescans just that dir. `working_repo_path` only binds the repo sessions run
 * in; it is NOT scanned. This is the common "add a project" flow.
 */
async clCreateProject(name: string, workingRepoPath: string | null, description: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_create_project", { name, workingRepoPath, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Hard-delete a project: purges the `projects` row + all child CL rows
 * (`cl_index`/`cl_folders`/`cl_reads` cascade). When `delete_cl_dir` is set AND
 * the project uses the default managed location (no custom `cl_path`), its
 * on-disk dir under `library/projects/` is removed too. A custom `cl_path`
 * (an external folder / repo) is NEVER touched — the flag is ignored for it.
 */
async clDeleteProject(name: string, deleteClDir: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_delete_project", { name, deleteClDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename a project: repoint the row + all child CL rows from `name` to
 * `new_name`, and (for a managed default-convention project) rename its on-disk
 * dir `library/projects/<name>/` -> `<new_name>/`. A custom `cl_path` keeps
 * pointing at the same external folder (only the project identifier changes).
 */
async clRenameProject(name: string, newName: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_rename_project", { name, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new empty file. Parent dir must exist; the file must not. The
 * frontend follows with `cl_rescan` to index it.
 */
async clCreateFile(project: string, filePath: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_create_file", { project, filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new directory. Parent dir must exist; the directory must not.
 */
async clMkdir(project: string, folderPath: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_mkdir", { project, folderPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename / move a file or folder within the project's CL root. Source must
 * exist; destination's parent must exist and the destination must not.
 */
async clRename(project: string, fromPath: string, toPath: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_rename", { project, fromPath, toPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a file, or a folder and everything under it. Must exist + resolve
 * inside the project root. Destructive — the frontend gates this behind a
 * confirmation dialog. Does NOT reconcile the index itself: the caller must
 * follow with `cl_rescan` to drop the now-orphaned `cl_index`/`cl_folders`
 * rows (the frontend does at ContextLibrary.tsx). A future agent/driver path
 * that deletes without rescanning would leave orphan rows until the next one.
 */
async clDeletePath(project: string, path: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cl_delete_path", { project, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getToolGateKeywords() : Promise<Result<GatedKeyword[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tool_gate_keywords") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setToolGateKeywords(keywords: GatedKeyword[]) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_tool_gate_keywords", { keywords }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGeneralPolicy() : Promise<Result<Policy, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_general_policy") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGeneralPolicy(policy: Policy) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_general_policy", { policy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProjectPolicy(project: string) : Promise<Result<Policy, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_project_policy", { project }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setProjectPolicy(project: string, policy: Policy) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_project_policy", { project, policy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSessionPolicy(sessionId: string) : Promise<Result<Policy, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session_policy", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSessionPolicy(sessionId: string, policy: Policy) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_session_policy", { sessionId, policy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the session's frozen Tool-Gate keyword list. Mirrors
 * [`get_session_policy`]'s fallback: the snapshot's `tool_gate` when seeded,
 * else the GLOBAL `tool-gate.json` (what a fresh spawn would seed + what the
 * hook falls back to). User-only.
 */
async getSessionToolGate(sessionId: string) : Promise<Result<GatedKeyword[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session_tool_gate", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Override the session's Tool-Gate keywords for THIS session only — the exact
 * mirror of [`set_session_policy`], swapping the preserved field: it keeps the
 * snapshot's [`Policy`] and replaces `tool_gate`. When no snapshot exists yet,
 * the Policy is seeded from the resolved blueprint (NOT defaulted) so the
 * inherited push/force/forbidden values aren't lost. Blank keywords are
 * dropped, matching the global Tool-Gate editor. The enforcement hook sources
 * from this snapshot first, so the change is live on the next Bash call.
 */
async setSessionToolGate(sessionId: string, keywords: GatedKeyword[]) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_session_tool_gate", { sessionId, keywords }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the full enforcement audit trail (`<data_dir>/.local/violations.jsonl`)
 * for the Settings → Violations viewer. Parse-tolerant (the reader skips
 * malformed lines); empty when the log doesn't exist yet.
 */
async readViolations() : Promise<Result<ViolationRecord[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_violations") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async claudeConfigRead() : Promise<Result<ClaudeConfigView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("claude_config_read") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getClaudeOverrides() : Promise<Result<ClaudeOverrides, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_claude_overrides") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setClaudeOverrides(overrides: ClaudeOverrides) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_claude_overrides", { overrides }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set/remove a string-valued settings.json key (e.g. `effortLevel`,
 * `editorMode`, `env.CLAUDE_CODE_MAX_OUTPUT_TOKENS`). `None` removes it.
 */
async claudeConfigSetString(key: string, value: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("claude_config_set_string", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set/remove a bool-valued settings.json key (e.g. `alwaysThinkingEnabled`,
 * `voiceEnabled`). `None` removes it.
 */
async claudeConfigSetBool(key: string, value: boolean | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("claude_config_set_bool", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enable/disable a plugin globally in `enabledPlugins` (`None` removes the
 * entry → marketplace default).
 */
async claudeConfigSetPluginEnabled(key: string, enabled: boolean | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("claude_config_set_plugin_enabled", { key, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveChoice(choiceId: string, picked: string, confirmStale: boolean) : Promise<Result<ResolveResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_choice", { choiceId, picked, confirmStale }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * All tray rows for a session, oldest-first (the Tab filters/render decide
 * what to show). Reads the durable table via the bridge, so it survives
 * restarts and includes resolved history.
 */
async listSessionTray(sessionId: string) : Promise<Result<SessionTrayView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_session_tray", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * All pending tray rows for OPEN sessions across the whole app — powers the
 * header notifier's per-session "needs your input [N]" counts. Durable, so it
 * survives a restart (unlike the in-memory `list_pending_choices`). Closed
 * sessions are excluded so dead-session pending isn't
 * surfaced as noise.
 */
async listPendingTray() : Promise<Result<SessionTrayView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_pending_tray") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * All findings for a session, oldest-first. The banner computes the open-
 * blocking count + escalation state; a future detail view can show the rest.
 */
async listSessionFindings(sessionId: string) : Promise<Result<FindingView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_session_findings", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionDocSearch(sessionId: string, query: string | null, phase: string | null) : Promise<Result<SessionDocumentView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_doc_search", { sessionId, query, phase }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `git diff --no-color <session_start_sha>` (falling back to
 * `git diff HEAD` if the anchor was never captured) inside the session's
 * `working_repo_path`, then classify each line via [`parse_diff_lines`].
 * 
 * Returns an empty `lines` Vec with a note if the diff is empty, the
 * session isn't running, or the session has no working repo. Errors only
 * when the git invocation itself can't be spawned.
 */
async computeApplyDiff(sessionId: string) : Promise<Result<ComputeApplyDiffResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("compute_apply_diff", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Summarize a session document via a one-shot, headless `claude -p` call —
 * a TL;DR for users who don't want to read the full I/P/A/V doc. The model is
 * resolved from `default_model_id` (app settings), falling back to the
 * session's Brian model, then Brian's agent config (same chain the live agents
 * use, via [`resolve_spawn_config`]). Bounded by a 60s timeout; the child is
 * killed on drop. Runs `--max-turns 1 --strict-mcp-config` so it cannot loop,
 * use tools, or touch MCP — a pure text response.
 */
async summarizeSessionDoc(sessionId: string, slug: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("summarize_session_doc", { sessionId, slug }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pre-flight check a saved model before a session uses it (B5): a one-shot,
 * headless `claude -p` ping through the model's resolved env (token + gateway,
 * via the same normalizing proxy live agents use). Surfaces a bad token, wrong
 * model id, or unreachable gateway at configure-time instead of as a silent
 * mid-session API error. Bounded by a 30s timeout; the child is killed on drop.
 */
async validateModel(modelId: string) : Promise<Result<ValidateResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch + validate a manifest WITHOUT installing — the consent step.
 * The PluginManager calls this first, shows the user what the plugin
 * requests, and only calls `install_plugin` after an explicit confirm.
 */
async previewPluginManifest(source: string) : Promise<Result<PluginManifestPreview, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_plugin_manifest", { source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installPlugin(source: string) : Promise<Result<InstalledPluginView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_plugin", { source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listInstalledPlugins() : Promise<Result<InstalledPluginView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_installed_plugins") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async enablePlugin(pluginId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enable_plugin", { pluginId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async disablePlugin(pluginId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disable_plugin", { pluginId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async uninstallPlugin(pluginId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("uninstall_plugin", { pluginId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Heartbeat feed, called by the frontend PluginHost's 5s ping loop just
 * before it postMessages `bhq:ping` into the plugin iframe. The backend
 * sweep loop (main.rs) turns unanswered pings into Slow/Crashed.
 */
async pluginNotePing(pluginId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin_note_ping", { pluginId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Heartbeat feed, called when the plugin iframe answers with `bhq:pong`
 * (and on clean PluginHost unmount, so a mid-flight ping isn't counted
 * as a miss against a plugin that simply closed with its panel).
 */
async pluginNotePong(pluginId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin_note_pong", { pluginId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pluginInvokeProxy(pluginId: string, command: string, argsJson: string | null) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin_invoke_proxy", { pluginId, command, argsJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkForUpdate() : Promise<Result<UpdateInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AgentConfigView = { agent_name: string; provider: string; model_name: string; base_url: string | null; auth_token: string | null; updated_at: string }
/**
 * One chat message in the chronological stream. Mirrors `storage::Message`
 * with `created_at` left as a string (ISO) so the frontend can parse with
 * whatever date library it picks.
 */
export type AgentMessage = { id: number; session_id: string; author: string; kind: string; content: string; created_at: string }
/**
 * The override set for one agent (or the `_all` fan-out default).
 */
export type AgentOverride = { 
/**
 * skill name → visibility. Maps to `skillOverrides` in `--settings`.
 */
skills?: Partial<{ [key in string]: SkillVisibility }>; 
/**
 * plugin key (`name@marketplace`) → enabled. Maps to `enabledPlugins`.
 */
plugins?: Partial<{ [key in string]: boolean }>; 
/**
 * MCP server name → forwarded. `false` removes it from the agent's mcp-config.
 */
mcp?: Partial<{ [key in string]: boolean }>; 
/**
 * Effort level (low/medium/high/xhigh/max). Maps to `CLAUDE_CODE_EFFORT_LEVEL`.
 */
effort?: string | null; 
/**
 * ultracode toggle. Maps to `"ultracode": true` in `--settings`.
 */
ultracode?: boolean | null; 
/**
 * Disable auto-memory. Maps to `CLAUDE_CODE_DISABLE_AUTO_MEMORY=1`.
 */
disable_auto_memory?: boolean | null; 
/**
 * Disable ALL CLAUDE.md autodiscovery. Maps to `CLAUDE_CODE_DISABLE_CLAUDE_MDS=1`.
 */
disable_claude_md?: boolean | null }
export type AppError = 
/**
 * Bad input. Frontend should highlight the offending field if it knows
 * which one. Otherwise a toast.
 */
{ kind: "Validation"; message: string } | 
/**
 * Resource doesn't exist (404-ish). Frontend can redirect or show empty
 * state.
 */
{ kind: "NotFound"; message: string } | 
/**
 * Authentication / authorization failure (e.g., trying to call a HANDS-
 * only tool from EYES, or a plugin missing a capability grant).
 */
{ kind: "Unauthorized"; message: string } | 
/**
 * Unexpected error not classified elsewhere. Toast with the message.
 */
{ kind: "Internal"; message: string } | 
/**
 * Sqlite write/read failure. Toast + log + offer retry.
 */
{ kind: "DbError"; message: string } | 
/**
 * Tauri capability check denied a plugin's request.
 */
{ kind: "CapabilityDenied"; message: string } | 
/**
 * Resource already exists (409-ish). Used by plugin install when the
 * target id is already on disk; frontend can offer "reinstall" UX.
 */
{ kind: "Conflict"; message: string }
/**
 * One consent-screen row: a requested capability + what granting it means,
 * in user terms (from the catalog).
 */
export type CapabilityDescription = { name: string; description: string }
export type ClFileContentView = { project: string; file_path: string; content: string; 
/**
 * Byte size of the file as it lives on disk. The `content` field is
 * the full text — included as a sanity check for the frontend.
 */
size_bytes: number; 
/**
 * True when the file was truncated because it exceeded the read cap.
 * Frontend can show a "showing first 1 MB" notice and offer to open
 * in $EDITOR (deferred).
 */
truncated: boolean; 
/**
 * True when the on-disk bytes were NOT valid UTF-8, so `content` is a
 * lossy decode (`from_utf8_lossy` had to allocate replacement chars).
 * The editor must refuse to save such a file — writing the lossy
 * content back would corrupt the original bytes.
 */
binary: boolean }
export type ClFolderView = { id: number; project_id: string; folder_path: string; description: string; tags: string | null; created_at: string; updated_at: string }
export type ClIndexEntryView = { id: number; project_id: string; file_path: string; description: string; tags: string | null; created_at: string; updated_at: string }
/**
 * One project's open-proposal tally for the Context Manager sidebar badges.
 * Projects with zero open proposals are absent from the list.
 */
export type ClProposalCountView = { project_id: string; open_count: number }
export type ClProposalView = { id: number; proposal_uid: string; project: string; file_path: string; kind: string; target_excerpt: string | null; proposed_body: string; evidence: string; status: string; proposed_by: string; session_id: string | null; created_at: string; updated_at: string }
export type ClRescanReportView = { added: string[]; touched: string[]; orphaned: string[] }
/**
 * The full resolved view of the user's Claude Code config.
 */
export type ClaudeConfigView = { 
/**
 * Resolved config dir (CLAUDE_CONFIG_DIR or `~/.claude`).
 */
config_dir: string; 
/**
 * "CLAUDE_CONFIG_DIR" if the env var is set, else "default (~/.claude)".
 */
config_dir_source: string; 
/**
 * `~/.claude.json` exists (the file claude-code actually loads MCP from).
 */
home_claude_json: FileStat; 
/**
 * A managed/enterprise policy was detected (it beats everything, incl. bot-hq).
 */
managed_settings_present: boolean; core_knobs: SettingItem[]; skills: SkillItem[]; plugins: PluginItem[]; mcp_servers: McpServerItem[]; memory: MemoryView; permissions: PermissionsView; 
/**
 * Non-fatal notices (unparseable files, ignored mcpServers, managed policy…).
 */
warnings: string[] }
/**
 * The full override store: a fan-out `_all` default plus per-agent entries.
 */
export type ClaudeOverrides = { _all?: AgentOverride; brian?: AgentOverride; rain?: AgentOverride }
/**
 * Result of `compute_apply_diff`: the classified diff lines plus an
 * optional human-readable note (e.g., the session-start anchor was lost
 * and we fell back to `git diff HEAD`).
 */
export type ComputeApplyDiffResult = { lines: DiffLine[]; note: string | null }
/**
 * One classified line of a unified `git diff`. `kind` is one of
 * `"add" | "remove" | "hunk" | "file" | "context"` — order-sensitive
 * classification per [`parse_diff_lines`].
 */
export type DiffLine = { kind: string; text: string }
/**
 * Stat for a single config file (present / path / size).
 */
export type FileStat = { present: boolean; path: string; bytes: number }
/**
 * One `findings` row projected for the frontend. snake_case (no `rename_all`),
 * like `SessionTrayView` — the generated TS reads `finding_uid` / `code_ref` /
 * etc. directly.
 */
export type FindingView = { id: number; session_id: string; finding_uid: string; agent: string; severity: string; summary: string; code_ref: string | null; status: string; disposition_reason: string | null; disposed_by: string | null; created_at: string; updated_at: string; 
/**
 * Times EYES raised this finding; `>= 2` = escalated (banner emphasis).
 */
raise_count: number; 
/**
 * True once EYES confirmed the resolution via `approve_finding`.
 */
eyes_approved: boolean }
/**
 * Force-push gate.
 */
export type ForcePushMode = 
/**
 * `git push --force` / `--force-with-lease` denied.
 */
"blocked" | 
/**
 * Permissive default — no policy file = no enforcement. The user opts into
 * blocking by writing `force_push: blocked` in policy.yaml.
 */
"allowed"
/**
 * How a matching Bash command is handled.
 */
export type GateMode = 
/**
 * Block the agent's direct Bash call (PreToolUse exit 2) and route it to
 * the `action_gate` MCP tool, which surfaces Approve/Reject and — on
 * approve — executes the command server-side.
 */
"gate" | 
/**
 * Let the command run normally (PreToolUse exit 0). Used to make
 * `git commit` / `git push` frictionless.
 */
"auto_allow"
/**
 * One global keyword entry.
 */
export type GatedKeyword = { 
/**
 * Case-insensitive substring matched against the tool name OR command.
 */
keyword: string; mode: GateMode }
/**
 * Which agents pick up a given config surface from `~/.claude` at spawn, and
 * which don't. Drives the per-surface inheritance badges in the UI. This is
 * the canonical mapping derived from `spawn.rs::build_command` behavior: both
 * agents run full claude-code and inherit skills/plugins/hooks/CLAUDE.md
 * (Rain's tool access is gated server-side, not by skipping inheritance);
 * model/permissions are overridden per-agent by bot-hq.
 */
export type Inheritance = { 
/**
 * Agents that inherit this surface from `~/.claude` at spawn.
 */
inherited_by: string[]; 
/**
 * Agents that do NOT — because bot-hq overrides the surface per-agent.
 */
skipped_by: string[]; 
/**
 * Short human note for the badge tooltip.
 */
note: string; 
/**
 * Whether bot-hq can override this surface per-agent at spawn (Phase 2).
 */
overridable: boolean }
/**
 * What the frontend sees for each installed plugin. Combines DB row state,
 * parsed manifest, and live heartbeat status.
 */
export type InstalledPluginView = { id: string; name: string; version: string; enabled: boolean; status: PluginStatus; manifest: PluginManifest; dir_path: string; installed_at: string }
/**
 * One MCP server visible to the user's claude-code, with the trap flagged.
 */
export type McpServerItem = { name: string; 
/**
 * "http" | "sse" | "stdio" | "unknown".
 */
transport: string; 
/**
 * Human source: "~/.claude.json", "~/.claude/settings.json (ignored)", "both".
 */
loaded_from: string; 
/**
 * Whether claude-code actually loads it (settings.json mcpServers is ignored).
 */
effective: boolean; 
/**
 * Masked one-line detail (url or command), secrets redacted.
 */
detail: string; 
/**
 * Agents bot-hq forwards it into (Brian; reserved keys excluded).
 */
forwarded_to_agents: string[]; 
/**
 * True if bot-hq filters this server from agents (bot-hq / claude-in-chrome).
 */
reserved_filtered: boolean }
/**
 * CLAUDE.md + auto-memory presence summary.
 */
export type MemoryView = { 
/**
 * `<config_dir>/CLAUDE.md` (user-global instructions).
 */
user_claude_md: FileStat; 
/**
 * `~/CLAUDE.md` (home-root, project-checked-in global rules).
 */
home_claude_md: FileStat; 
/**
 * Number of `projects/<slug>/memory/` dirs with a MEMORY.md.
 */
projects_with_memory: number; inheritance: Inheritance }
/**
 * Frontend-facing shape of a saved model. `auth_token` is exposed (the desktop
 * UI is local + trusted, like the AgentCard token field).
 */
export type ModelView = { id: string; display_name: string; provider: string; model_name: string; base_url: string | null; auth_token: string | null; created_at: string; updated_at: string }
/**
 * Permission posture summary (counts only; bot-hq overrides per agent anyway).
 */
export type PermissionsView = { default_mode: string | null; allow: number; ask: number; deny: number; additional_directories: number; inheritance: Inheritance }
/**
 * One installed plugin and its enablement.
 */
export type PluginItem = { 
/**
 * `name@marketplace` key as used in `enabledPlugins`.
 */
key: string; enabled: boolean; inheritance: Inheritance }
export type PluginManifest = { id: string; name: string; version: string; entry: string; 
/**
 * Plugin-API contract version (the grantable-command catalog +
 * postMessage RPC shape). This binary supports exactly 1; parsing
 * rejects anything else so an old bot-hq can't half-run a newer
 * plugin. Omitted in JSON = 1.
 */
api_version?: number; requested_capabilities?: string[]; slots?: PluginSlot[] }
/**
 * What the install-consent dialog renders before anything lands on disk.
 */
export type PluginManifestPreview = { manifest: PluginManifest; capabilities: CapabilityDescription[] }
export type PluginSlot = { 
/**
 * React shell slot name (e.g., "sidebar.bottom"). `None` means the
 * plugin contributes a dedicated panel via [`panel_route`] instead.
 */
slot_name: string | null; 
/**
 * Frontend router path for a dedicated panel. `None` means slot-only.
 */
panel_route: string | null }
/**
 * Internally-tagged so the TS surface is a discriminated union on `kind`:
 * `{kind:"Healthy"} | {kind:"Slow", miss_count:N} | {kind:"Crashed"}`.
 */
export type PluginStatus = 
/**
 * Last ping got a pong within the window.
 */
{ kind: "Healthy" } | 
/**
 * One or more misses, below MISS_LIMIT.
 */
{ kind: "Slow"; miss_count: number } | 
/**
 * MISS_LIMIT consecutive misses — host should tear down the iframe.
 */
{ kind: "Crashed" }
/**
 * Resolved policy for a (general + per-project) overlay, or a session snapshot.
 */
export type Policy = { 
/**
 * Words/phrases that must not appear in commit messages or staged diffs.
 * Pre-commit grep blocks the commit if any match.
 */
forbidden_in_commits?: string[]; 
/**
 * `git push` gate. `auto` = pushes go through; `ask` = the pre-push hook
 * surfaces a per-push Approve/Reject prompt to the user and blocks on their
 * pick (the user may also flip the Session Settings toggle to `auto`).
 */
push_gate?: PushGateMode; 
/**
 * Force-push gate. `blocked` = `git push --force`/`--force-with-lease`
 * denied; `allowed` = permitted (still subject to `push_gate`).
 */
force_push?: ForcePushMode; 
/**
 * Bash commands that always require approval — `request_approval`
 * kind="per_action", every invocation.
 */
per_action_approval?: string[]; 
/**
 * Regex pattern branch names must match. Empty = no constraint.
 */
branch_pattern?: string; 
/**
 * Free-form commit style note.
 * Surfaced to the agent in its system prompt.
 */
commit_style?: string }
/**
 * Shared spawn logic for both fresh and existing sessions: spawn Brian + Rain,
 * kick the duo pumps, return the handle.
 * Resolve a session's project from its repo paths. A registered project
 * whose `working_repo_path` matches wins (matched against the BASE repo
 * first — a worktree session's path ends in the repo basename, not
 * necessarily the project name); the path basename stays as the fallback
 * for unregistered repos. Repo-less sessions resolve to `None` (general
 * policy applies by inheritance).
 * How a session's project name was derived from its repo path — surfaced in
 * the gear tab (policy-origin badge) so the user can see WHY a session
 * inherited a given policy. The 2026-06-11 "why the full forbidden list?"
 * surprise was an unregistered repo silently resolving to general policy.
 */
export type ProjectProvenance = 
/**
 * Matched a registered project's working-repo path (canonical compare).
 */
"registered" | 
/**
 * No registered match — fell back to the repo's path basename.
 */
"inferred" | 
/**
 * Repo-less session — no project; general policy applies by inheritance.
 */
"none"
/**
 * Project as exposed to the frontend. Drives the project-filter dropdown
 * in ContextLibrary and (eventually) the New-Session repo picker.
 */
export type ProjectView = { name: string; display_name: string; working_repo_path: string | null; description: string | null; 
/**
 * Custom CL root. NULL/None = default convention
 * `<data_dir>/projects/<name>/`. Lets the folder-view show whether a
 * project was registered at an arbitrary on-disk location.
 */
cl_path: string | null }
/**
 * `git push` gate. Set per tier (global/project/session); a session inherits
 * the resolved value at spawn then can flip it in the gear tab. No per-branch
 * memory — the user toggles `auto` to enable pushes for the session.
 */
export type PushGateMode = 
/**
 * No prompt — pushes go through.
 */
"auto" | 
/**
 * Pushes are gated — the pre-push hook surfaces a per-push Approve/Reject
 * prompt and blocks on the user's pick (fail-closed if the app is
 * unreachable). The user may also flip the session toggle to `auto`.
 */
"ask"
/**
 * Outcome of resolving a choice. `NeedsStaleConfirm` means the pick would run a
 * gated command whose requesting agent has moved on (client timeout / restart)
 * — nothing ran; the UI must confirm (the command may be invalid/destructive
 * against a changed repo) and re-call with `confirm_stale = true`.
 */
export type ResolveResult = { kind: "resolved" } | { kind: "needs_stale_confirm"; command: string; asked_at: string | null }
/**
 * Aggregated `cl_retrieve` telemetry for the Context Library measurement card
 * (Stage 4b). Mirrors [`crate::storage::RetrievalStats`]; the ratios are the
 * "is the CL helping" signals — avg tokens/session is the tokens-per-task
 * proxy, stale-hit + empty-return rates should trend toward 0.
 */
export type RetrievalStatsView = { event_count: number; distinct_sessions: number; total_tokens: number; total_atoms: number; stale_hits: number; empty_returns: number; avg_tokens_per_event: number; avg_tokens_per_session: number; stale_hit_rate: number; empty_return_rate: number }
/**
 * Per-session create-dialog picks beyond the positional args. Bundled into
 * one struct because `create_session` sits at tauri-specta's 10-arg command
 * limit; every field is `None` = inherit the configured default.
 * (Renamed from `SessionEffortChoices` when `use_worktree` joined.)
 */
export type SessionCreateOptions = { brianEffort: string | null; rainEffort: string | null; brianUltracode: boolean | null; rainUltracode: boolean | null; 
/**
 * Run the session in an isolated git worktree (None → the
 * `worktree_default` app setting, which defaults ON for repo-backed
 * sessions).
 */
useWorktree: boolean | null }
/**
 * Uncommitted-work probe for the close-confirm dialog: how many entries
 * `git status --porcelain` reports in the session's working tree. `has_repo`
 * is false for a repo-less session (nothing to warn about). Best-effort —
 * never an error path that could block closing. Return struct uses snake_case
 * (mirrors `SessionInfo`); the React side reads `has_repo` / `dirty_count`.
 */
export type SessionDirty = { has_repo: boolean; dirty_count: number }
export type SessionDocumentView = { id: number; session_id: string; slug: string; body: string; created_at: string; updated_at: string; phase: string | null }
export type SessionInfo = { id: string; title: string; working_repo_path: string | null; 
/**
 * Set when the session runs in an isolated git worktree —
 * `working_repo_path` is then the worktree and this is the repo it was
 * carved from. None = direct mode.
 */
base_repo_path: string | null; archived: boolean; created_at: string; closed_at: string | null; brian_model_at_spawn: string | null; rain_model_at_spawn: string | null; 
/**
 * False = solo-Brian session (Rain disabled at create).
 */
rain_enabled: boolean; 
/**
 * First line preview of the latest text message + its author, for the
 * dashboard Quickview. Both None on the closed-session and external
 * JSON-RPC paths — only the dashboard `list_sessions` command populates
 * them (via `list_active_sessions_with_preview`).
 */
last_message: string | null; last_author: string | null }
export type SessionProjectInfo = { 
/**
 * Resolved project name, or None for a repo-less session.
 */
project: string | null; 
/**
 * How `project` was derived — drives the gear-tab policy-origin badge.
 */
provenance: ProjectProvenance }
/**
 * Current runtime state (derived activity + per-agent health) for every LIVE
 * session — a snapshot the frontend BACKFILLS its event-driven activity/health
 * stores from on mount. Those stores are seeded only by `session:activity` /
 * `session:agent_health` events, which fire on transitions and can be missed
 * during the respawn window before the React listeners mount (Bug C: footer /
 * tiles / input-indicator left stale until the next transition). snake_case
 * return (mirrors `SessionInfo`); React reads `session_id`/`activity`/
 * `brian_health`/`rain_health`.
 */
export type SessionRuntime = { session_id: string; activity: string; 
/**
 * Per-agent busy flags (the derived `activity` collapses them) so the chat
 * input can label which agent is working after a backfill, not just guess.
 */
brian_busy: boolean; rain_busy: boolean; brian_health: string | null; rain_health: string | null; 
/**
 * Peer-forward router liveness (duo only). `None` = solo, or never reported
 * (assume alive — the event fires only on change). Seeds the UI router dot.
 */
router_alive: boolean | null }
/**
 * One durable `session_tray` row, projected for the session-view Tray tab.
 * Unlike the live in-memory pending view (`list_pending_choices`), this
 * surfaces every tray item for the session — pending AND resolved history —
 * so the tab shows what accumulated even across restarts.
 */
export type SessionTrayView = { id: number; session_id: string; choice_id: string; agent: string; kind: string; prompt: string; options: string[]; status: string; picked_option: string | null; 
/**
 * The gated command (action_gate / ToolBlocklist approvals); null otherwise.
 */
command_text: string | null; asked_at: string; answered_at: string | null; 
/**
 * True when this is a PENDING gated command whose requesting agent has moved
 * on (client timeout / restart) — approving runs the command blind, so the
 * UI warns + requires confirm. Computed at list time from the live in-memory
 * pending map (false from the bare `From` conversion; the list commands set it).
 */
stale: boolean }
/**
 * One scalar/env setting with provenance + inheritance.
 */
export type SettingItem = { 
/**
 * Dotted settings key, e.g. `effortLevel` or `env.CLAUDE_CODE_MAX_OUTPUT_TOKENS`.
 */
key: string; label: string; 
/**
 * Effective value (masked if secret). `None` = unset (uses default).
 */
value: string | null; 
/**
 * Where the value resolved from, or "unset (default)".
 */
source: string; inheritance: Inheritance }
/**
 * One skill (user-dir skill or plugin-bundled skill).
 */
export type SkillItem = { name: string; 
/**
 * "user" (a dir under `<config>/skills/`) or "plugin" (bundled).
 */
kind: string; 
/**
 * From SKILL.md frontmatter `disable-model-invocation` (user skills).
 */
disable_model_invocation: boolean; description: string | null; 
/**
 * SKILL.md path (user skills only).
 */
path: string | null; inheritance: Inheritance }
/**
 * Per-skill visibility — mirrors claude-code's `skillOverrides` states.
 */
export type SkillVisibility = 
/**
 * Default — listed to the model + in the `/` menu.
 */
"on" | 
/**
 * Name only listed to the model; still in the `/` menu.
 */
"name-only" | 
/**
 * Hidden from the model (no auto-invoke); still manually invocable.
 */
"user-invocable-only" | 
/**
 * Fully disabled (no auto-invoke, not in the `/` menu).
 */
"off"
/**
 * Update status reported to the frontend. snake_case fields (mirrors the
 * `SessionInfo` return-type convention) — the React side reads these names.
 */
export type UpdateInfo = { current_version: string; latest_version: string; update_available: boolean; release_url: string; release_notes: string | null; published_at: string | null }
/**
 * Outcome of a pre-flight model probe (B5).
 */
export type ValidateResult = { ok: boolean; message: string }
export type ViolationKind = 
/**
 * `git push` intercepted by push_gate policy.
 */
"push_gate" | 
/**
 * `git commit` proposed message contained a forbidden word.
 */
"commit_grep" | 
/**
 * `git push --force` / `--force-with-lease`.
 */
"force_push" | 
/**
 * Tool Gate / `action_gate` approval (legacy wire name `tool_blocklist`,
 * kept for back-compat; the per-project `tool_blocklist` it was named for
 * is retired — see the Tool Gate).
 */
"tool_blocklist" | 
/**
 * Bash command matched `per_action_approval`.
 */
"per_action" | 
/**
 * Generic agent-initiated approval request (free-form).
 */
"generic_approval" | 
/**
 * A policy.yaml file was modified outside the Settings UI flow.
 * Audit-only in v1 — we log but don't block (yet). Catches the
 * "agent edits policy.yaml to remove forbidden words" attack.
 */
"policy_mutation" | 
/**
 * A `git commit` / `git push` blocked by the EYES-sign-off gate — HANDS
 * tried to ship with unresolved EYES `blocking` findings. Logged Denied by
 * the pre-commit / pre-push hook on a block.
 */
"findings"
export type ViolationOutcome = "approved" | "denied" | 
/**
 * User dismissed/canceled before deciding (e.g., closed dialog).
 */
"abandoned" | 
/**
 * Audit-only — we observed an event but didn't ask for approval.
 * Used for PolicyMutation entries (no user prompt; just logged).
 */
"detected"
export type ViolationRecord = { ts: string; session_id: string; agent: string; kind: ViolationKind; action: string; outcome: ViolationOutcome; detail?: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
