/**
 * The color scheme `index.css` declares to the browser.
 *
 * `<select>` popups, scrollbars, spinners and date pickers are drawn by the
 * platform, not by this stylesheet. Without a `color-scheme` declaration they
 * follow the HOST theme — and bot-hq has no light mode for the host to be
 * wrong about: zero `dark:` variants, no `darkMode` in the Tailwind config, no
 * `dark` class on `<html>`.
 *
 * Found on Fedora/KDE (2026-08-25): the AppImage's GTK hook probes GNOME's
 * `org.gnome.desktop.interface gtk-theme`, reads `'Breeze'`, finds no "dark"
 * substring and exports `GTK_THEME=Adwaita:light` — so WebKitGTK drew the
 * phase `<select>` as a light pill in a dark header, on a desktop that is
 * itself dark (`color-scheme` = `'prefer-dark'`). That hook is regenerated by
 * linuxdeploy on every build and is not in this repo, so patching it would fix
 * one machine and ship nothing. The portable lever is the declaration, and it
 * covers the same latent bug on a light-mode Windows or macOS host.
 *
 * `theme.test.ts` reads the real `index.css` through this function.
 */

/**
 * The value of the LAST `color-scheme` declaration inside a `:root { … }`
 * block, or `null` when `:root` declares none.
 *
 * Last rather than first because that is what the cascade resolves to within
 * one block — a test asserting the first would pass a stylesheet whose
 * effective value is something else.
 */
export function rootColorScheme(css: string): string | null {
  // Comments first: a matcher run over raw text accepts
  // `:root { /* color-scheme: dark; */ }` and reports "dark" for a
  // stylesheet that declares nothing — a pin that passes on a broken file is
  // worse than no pin.
  const stripped = css.replace(/\/\*[\s\S]*?\*\//g, "");
  const blocks = stripped.match(/:root\s*\{[^}]*\}/g) ?? [];
  let found: string | null = null;
  for (const block of blocks) {
    // The `(?:^|[;{])` boundary is load-bearing: without it
    // `--brand-color-scheme: dark` and `-webkit-color-scheme: dark` both
    // satisfy the pin, and a vendor prefix no engine honours is exactly the
    // shape that would leave the bug shipped while the test stayed green.
    for (const m of block.matchAll(/(?:^|[;{])\s*color-scheme\s*:\s*([^;}]+)/g)) {
      found = m[1].trim();
    }
  }
  return found;
}
